### ISSUE TITLE
SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)

### ISSUE THREAD

**Issue by ggoyea** [greenrobot/greenDAO#1033]
android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
#################################################################
Error Code : 1032 (SQLITE_READONLY_DBMOVED)
Caused By : Database or Journal file have been removed.
	(attempt to write a readonly database (code 1032))
#################################################################
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:683)
	at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
	at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
	at org.greenrobot.greendao.database.StandardDatabaseStatement.execute(StandardDatabaseStatement.java:30)
	at org.greenrobot.greendao.AbstractDao.updateInsideSynchronized(AbstractDao.java:808)
	at org.greenrobot.greendao.AbstractDao.update(AbstractDao.java:783)

**Comment by greenrobot-team** [comment]
That's your issue:
```
Error Code : 1032 (SQLITE_READONLY_DBMOVED)
Caused By : Database or Journal file have been removed.
	(attempt to write a readonly database (code 1032))
```

**Comment by ggoyea** [comment]
> That's your issue:
> 
> ```
> Error Code : 1032 (SQLITE_READONLY_DBMOVED)
> Caused By : Database or Journal file have been removed.
> 	(attempt to write a readonly database (code 1032))
> ```

ok,thanks.
