### ISSUE TITLE
When will Gradle later be supported?

### ISSUE THREAD

**Issue by deerGentler** [greenrobot/greenDAO#1061]
If I can't support a higher version, I will give up using green Dao because my project needs to be upgraded！

**Comment by greenrobot-team** [comment]
Is this about #1002? What Gradle version are you using? We can't help if you don't share details required to fix any issues.

**Comment by VigorousLiang** [comment]
Caused by: java.lang.NoSuchMethodError: 'org.gradle.api.tasks.TaskInputs org.gradle.api.tasks.TaskInputs.property(java.lang.String, java.lang.Object)'
	at org.greenrobot.greendao.gradle.Greendao3GradlePlugin.createGreendaoTask(Greendao3GradlePlugin.kt:60)
	at org.greenrobot.greendao.gradle.Greendao3GradlePlugin.access$createGreendaoTask(Greendao3GradlePlugin.kt:14)
	at org.greenrobot.greendao.gradle.Greendao3GradlePlugin$apply$1.execute(Greendao3GradlePlugin.kt:47)
	at org.greenrobot.greendao.gradle.Greendao3GradlePlugin$apply$1.execute(Greendao3GradlePlugin.kt:14)

**Comment by VigorousLiang** [comment]
gradle version classpath 'com.android.tools.build:gradle:4.2.0-beta01'
Long time ago, the pre-version gradle plugin remarked the method 'property' will be deleted in the future.
Now it comes.

**Comment by greenrobot-team** [comment]
This is exactly the issue described in #1002. Make sure to use the latest greenDAO release.
