### ISSUE TITLE
DaoGenerator.getConfiguration Exception

### ISSUE THREAD

**Issue by Duewang** [greenrobot/greenDAO#1108]
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':commonlib:greendao'.
Caused by: org.gradle.api.UncheckedIOException: java.io.UnsupportedEncodingException: UFT-8
Caused by: java.io.UnsupportedEncodingException: UFT-8
	at freemarker.cache.URLTemplateLoader.getReader(URLTemplateLoader.java:54)
	at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:547)
	at freemarker.cache.TemplateCache.getTemplateInternal(TemplateCache.java:439)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:292)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2798)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2647)
	at org.greenrobot.greendao.generator.DaoGenerator.getConfiguration(DaoGenerator.java:76)
	at org.greenrobot.greendao.generator.DaoGenerator.<init>(DaoGenerator.java:62)
	at org.greenrobot.greendao.codemodifier.Greendao3Generator.generateSchema(Greendao3Generator.kt:82)
	at org.greenrobot.greendao.codemodifier.Greendao3Generator.run(Greendao3Generator.kt:57)
	at org.greenrobot.greendao.gradle.Greendao3GradlePlugin$createGreendaoTask$$inlined$apply$lambda$1.execute(Greendao3GradlePlugin.kt:90)
	at org.greenrobot.greendao.gradle.Greendao3GradlePlugin$createGreendaoTask$$inlined$apply$lambda$1.execute(Greendao3GradlePlugin.kt:14)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:704)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:555)
```

**Comment by greenrobot-team** [comment]
It looks like you have the encoding incorrectly configured:
`java.io.UnsupportedEncodingException: UFT-8`

It should be `UTF-8`.

**Comment by Duewang** [comment]
DaoGenerator.getConfiguration is greenDao plugin. It is not compatible with androidstudio version.Plugin will work If you change the version of the android studio.

**Comment by Duewang** [comment]
DaoGenerator.getConfiguration is greenDao plugin. It is not compatible with androidstudio version.Plugin will work If you change the version of the android studio.

**Comment by Duewang** [comment]
> DaoGenerator.getConfiguration is greenDao plugin. It is not compatible with androidstudio version.Plugin will work If you change the version of the android studio.

**Comment by Duewang** [comment]
> It looks like you have the encoding incorrectly configured: `java.io.UnsupportedEncodingException: UFT-8`
> 
> It should be `UTF-8`.

DaoGenerator.getConfiguration is greenDao plugin. It is not compatible with androidstudio version.Plugin will work If you change the version of the android studio.
