### ISSUE TITLE
[Robolectric incompatibility] no such collation sequence: LOCALIZED

### ISSUE THREAD

**Issue by nachowski** [greenrobot/greenDAO#141]
Unfortunately running the following code leads to an exception in a Robolectric test:

    List<MyObject> airports = myDao.queryBuilder()
                .orderAsc(MyDao.Properties.I_AM_A_STRING)
                .list();
Exception:

    Caused by: com.almworks.sqlite4java.SQLiteException: [1] DB[2] prepare() SELECT T.'_id',T.'I_AM_A_STRING' FROM MYDAO T  ORDER BY T.'I_AM_A_STRING' COLLATE LOCALIZED ASC [no such collation sequence: LOCALIZED]
	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1309)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:487)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:542)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:529)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$2.call(ShadowSQLiteConnection.java:365)

The culprit is this line of code [in QueryBuilder.java](https://github.com/greenrobot/greenDAO/blob/master/DaoCore/src/de/greenrobot/dao/query/QueryBuilder.java#L193) that forces the `COLLATE LOCALIZED` option.

I am not sure if this should be fixed in Robolectric or in GreenDao (or in sqlite4java?). Currently the only workaround is to omit the `.orderAsc(MyDao.Properties.I_AM_A_STRING)` line and instead sort the results using `Collections.sort()` or similar.

[Related Robolectric issue](https://github.com/robolectric/robolectric/issues/1230)

**Comment by nachowski** [comment]
This has now been fixed in robolectric.
