### ISSUE TITLE
Some of my users are getting "android.database.sqlite.SQLiteException: Failed to change locale for db "

### ISSUE THREAD

**Issue by forlayo** [greenrobot/greenDAO#167]
The crash retrieved is:
```
java.lang.RuntimeException: Unable to create application com.yuilop.YuilopApplication: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/com.yuilop/databases/upptalk.db' to 'es_ES'.
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4643)
       at android.app.ActivityThread.access$1300(ActivityThread.java:165)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1433)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5391)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/com.yuilop/databases/upptalk.db' to 'es_ES'.
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:390)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:966)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:229)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
       at com.yuilop.database.DataBase.<init>(DataBase.java:103)
       at com.yuilop.database.DataBase.getInstance(DataBase.java:94)
       at com.yuilop.YuilopApplication.onCreate(YuilopApplication.java:70)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1069)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4640)
       at android.app.ActivityThread.access$1300(ActivityThread.java:165)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1433)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5391)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:552)
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:364)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:966)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:229)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
       at com.yuilop.database.DataBase.<init>(DataBase.java:103)
       at com.yuilop.database.DataBase.getInstance(DataBase.java:94)
       at com.yuilop.YuilopApplication.onCreate(YuilopApplication.java:70)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1069)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4640)
       at android.app.ActivityThread.access$1300(ActivityThread.java:165)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1433)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5391)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

I'm looking about solutions but I didn't see any info about this issue in greendao, I've found only one stackoverflow thread about same problem ( http://stackoverflow.com/questions/19491675/failed-to-change-locale-for-db-data-data-my-easymedi-controller-databases-easy ). 

But I didn't see openDatabase method in GreenDao neither found a way to apply the workaround.

**Comment by Groxx** [comment]
At the base of that chain of exceptions is an SQLiteDatabaseLockedException.  Are you perhaps making multiple SQLiteOpenHelper instances?

**Comment by HuJianChong** [comment]
I also encountered this problem. how did you solve the problem please?

**Comment by chengjiamei** [comment]
I also encountered this problem. how did you solve the problem please?

java.lang.RuntimeException:Unable to create application com.wearme.pureprac.WearApplication: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/com.wearme.pureprac/databases/futont' to 'zh_CN'.
--
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5058) ......
 Caused by:
 android.database.sqlite.SQLiteDatabaseLockedException:database is locked (code 5)
 android.database.sqlite.SQLiteConnection.nativeExecuteForString(Native Method)
 android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:650)
android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:379)
android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:223)
android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:198)
android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:864)
android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:849)
android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:742)
android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1306)
android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:279)
android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
com.wearme.pureprac.net.db.DaoUtils.<init>(Unknown Source)
com.wearme.pureprac.net.db.DaoUtils.getInstance(Unknown Source)
com.wearme.pureprac.WearApplication.init(Unknown Source)
com.wearme.pureprac.WearApplication.onCreate(Unknown Source)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5055)
android.app.ActivityThread.access$1700(ActivityThread.java:192)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
android.os.Handler.dispatchMessage(Handler.java:111)
android.os.Looper.loop(Looper.java:224)
android.app.ActivityThread.main(ActivityThread.java:5929)
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke(Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
