### ISSUE TITLE
attempt to re-open an already-closed object

### ISSUE THREAD

**Issue by sixgodIT** [greenrobot/greenDAO#293]
Such occasional error：
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.yunxiao.haofenshu/databases/yunxiao569f76d900000abc345533e6
	at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1342)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1285)
	at de.greenrobot.dao.query.Query.unique(Query.java:162)
	at de.greenrobot.dao.query.QueryBuilder.unique(QueryBuilder.java:410)
	at com.yunxiao.haofenshu.busness.impl.WrongSubjectImpl.getWrongSubject(WrongSubjectImpl.java:89)
	at com.yunxiao.haofenshu.error.fragment.SubjectErrorFragment.loadFromDb2Cache(SubjectErrorFragment.java:131)
	at com.yunxiao.haofenshu.error.fragment.SubjectErrorFragment.onCreateView(SubjectErrorFragment.java:76)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1072)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:554)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:513)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:494)
	at com.astuetz.PagerSlidingTabStrip$2.onClick(PagerSlidingTabStrip.java:257)
	at android.view.View.performClick(View.java:4908)
	at android.view.View$PerformClick.run(View.java:20378)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5691)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by sixgodIT** [comment]
This is an occasional problem。When I log out, I do something：
 public static synchronized DaoMaster getDaoMaster(Context context) {
        if (sDaoMaster == null) {
            String uid = getUserId();
            YxSQLiteOpenHelper sqLiteOpenHelper = new YxSQLiteOpenHelper(context, "yunxiao" + uid, null);
            sDaoMaster = new DaoMaster(sqLiteOpenHelper.getWritableDatabase());
        }
        return sDaoMaster;
    }
  public static synchronized void resetDaoMaster() {
        if (sDaoMaster != null) {
            sDaoMaster.getDatabase().close();
            sDaoMaster = null;
            DaoHelper.cleanup();
        }

    }

**Comment by sixgodIT** [comment]
How to avoid this problem？

**Comment by Groxx** [comment]
I'm going to guess that you have a line somewhere in your code equivalent to:
```java
final DaoMaster dao = App.getDaoMaster(this);
view.setOnClickListener(new View.OnClickListener() {
  onClick(...) {
    dao.doSomethingToTheDatabase();
  }
});
```

If so, your dao's db connection could be closed by logging out, and _then_ onClick fires, attempts to use the (closed) db, and fails.  Clicks sometimes arrive late, and fragment transactions don't happen immediately, so I'm going to guess you have some sequence of events that you aren't expecting that's leading to this.  Lots of seemingly-weird stuff can happen in Android when devices are overloaded and running slow.
