### ISSUE TITLE
android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)

### ISSUE THREAD

**Issue by Vivecstel** [greenrobot/greenDAO#348]
Hello :) I am getting the following exception from time to time when doing a lot of read / write on my db. Note that using background threads for db access though : 
- com.birbit.android.jobqueue.Job (instead of async task. I use this mostly in fragments to fetch database data or write some quick data in the database)
- android.app.IntentService(to write data in the database)
- android.app.job.JobService(to write/update datain the database)
So after heavy db usage a sometimes get the following crash : 

```
android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow (SQLiteConnection.java)
android.database.sqlite.SQLiteConnection.executeForCursorWindow (SQLiteConnection.java:843)
android.database.sqlite.SQLiteSession.executeForCursorWindow (SQLiteSession.java:836)
android.database.sqlite.SQLiteQuery.fillWindow (SQLiteQuery.java:62)
android.database.sqlite.SQLiteCursor.fillWindow (SQLiteCursor.java:143)
android.database.sqlite.SQLiteCursor.getCount (SQLiteCursor.java:132)
android.database.AbstractCursor.moveToPosition (AbstractCursor.java:219)
android.database.AbstractCursor.moveToNext (AbstractCursor.java:268)
de.greenrobot.dao.query.CountQuery.count (CountQuery.java:42)
de.greenrobot.dao.query.QueryBuilder.count (QueryBuilder.java:443)
com.steleot.seriez.database.daohelper.ErrorServiceDaoHelper.getErrorServiceCount (ErrorServiceDaoHelper.java:62)
com.steleot.seriez.services.ReRunErrorIntentService.onException (ReRunErrorIntentService.java:78)
com.steleot.seriez.services.base.BaseIntentService.onHandleIntent (BaseIntentService.java:41)
android.app.IntentService$ServiceHandler.handleMessage (IntentService.java:66)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.os.HandlerThread.run (HandlerThread.java:61)
```

I use a single dao session that I get from this singleton throughtout the application :

```
public class SeriezDaoHelper {

    /** seriez dao helper **/
    public static SeriezDaoHelper mInstance;
    /** dao session **/
    private DaoSession mDaoSession;

    private SeriezDaoHelper(Context context) {
        mInstance = this;
        SeriezOpenHelper seriezOpenHelper = new SeriezOpenHelper(context, "Seriez.db", null);
        SQLiteDatabase db = seriezOpenHelper.getWritableDatabase();
        DaoMaster daoMaster = new DaoMaster(db);
        mDaoSession = daoMaster.newSession();
    }

    public static SeriezDaoHelper getInstance(Context context) {
        if (mInstance == null) {
            mInstance = new SeriezDaoHelper(context);
        }
        return mInstance;
    }

    public DaoSession getSession() {
        return mDaoSession;
    }
}
```

**Comment by Vivecstel** [comment]
Switched to store the dao session to application class instead(not that it makes any difference from singleton) and limiting one background service usage to start only when application closes, seems to do the trick.

**Comment by aamir2590** [comment]
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:843)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:145)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:134)
       at de.greenrobot.dao.AbstractDao.loadAllFromCursor(SourceFile:371)
       at de.greenrobot.dao.AbstractDao.loadAllAndCloseCursor(SourceFile:184)
       at de.greenrobot.dao.InternalQueryDaoAccess.loadAllAndCloseCursor(SourceFile:21)
       at de.greenrobot.dao.query.Query.list(SourceFile:121)
       at de.greenrobot.dao.query.QueryBuilder.list(SourceFile:374)
       at com.touchtalent.bobbleapp.util.BobbleAppWorkUtil.logEventsToServer(SourceFile:448)
       at com.touchtalent.bobbleapp.handlers.BobbleKeyboardTaskRunnable$BobbleKeyboardTaskHandler.handleMessage(SourceFile:165)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at com.touchtalent.bobbleapp.handlers.BobbleKeyboardTaskRunnable.run(SourceFile:47)
       at java.lang.Thread.run(Thread.java:818)

**Comment by aamir2590** [comment]
## Even if we have store DaoSession Object in Application class, we are getting this exception. Can you please suggest any solution.

Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:843)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:145)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:134)
       at de.greenrobot.dao.AbstractDao.loadAllFromCursor(SourceFile:371)
       at de.greenrobot.dao.AbstractDao.loadAllAndCloseCursor(SourceFile:184)
       at de.greenrobot.dao.InternalQueryDaoAccess.loadAllAndCloseCursor(SourceFile:21)
       at de.greenrobot.dao.query.Query.list(SourceFile:121)
       at de.greenrobot.dao.query.QueryBuilder.list(SourceFile:374)
       at com.touchtalent.bobbleapp.util.BobbleAppWorkUtil.logEventsToServer(SourceFile:448)
       at com.touchtalent.bobbleapp.handlers.BobbleKeyboardTaskRunnable$BobbleKeyboardTaskHandler.handleMessage(SourceFile:165)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at com.touchtalent.bobbleapp.handlers.BobbleKeyboardTaskRunnable.run(SourceFile:47)
       at java.lang.Thread.run(Thread.java:818)

**Comment by greenrobot-team** [comment]
This is a [SQLite error](https://sqlite.org/c3ref/c_abort.html). I suggest to search for `SQLiteCantOpenDatabaseException: unable to open database file` on Google. -ut

**Comment by greenrobot-team** [comment]
@aamir2590 This is a [SQLite error](https://sqlite.org/c3ref/c_abort.html). I suggest to search for `SQLiteCantOpenDatabaseException: unable to open database file` on Google. -ut

**Comment by nAkhmedov** [comment]
I am facing this issue too on Android 8

`java.lang.RuntimeException:
at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6532)
at android.app.ActivityThread.-wrap2 (Unknown Source)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1963)
at android.os.Handler.dispatchMessage (Handler.java:108)
at android.os.Looper.loop (Looper.java:166)
at android.app.ActivityThread.main (ActivityThread.java:7425)
at java.lang.reflect.Method.invoke (Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:245)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:921)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException:
at android.database.sqlite.SQLiteConnection.nativeOpen (Native Method)
at android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:223)
at android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:207)
at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked (SQLiteConnectionPool.java:511)
at android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:194)
at android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:183)
at android.database.sqlite.SQLiteDatabase.openInner (SQLiteDatabase.java:880)
at android.database.sqlite.SQLiteDatabase.open (SQLiteDatabase.java:864)
at android.database.sqlite.SQLiteDatabase.openDatabase (SQLiteDatabase.java:767)
at android.app.ContextImpl.openOrCreateDatabase (ContextImpl.java:820)
at android.content.ContextWrapper.openOrCreateDatabase (ContextWrapper.java:299)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:266)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:206)
`

**Comment by rakhi191** [comment]
@nAkhmedov am facing same issue SQLiteCantOpenDatabaseException.
Did you find any solution ?
