### ISSUE TITLE
Execution failed for task ':app:greendao'. > Error processing "Chapter": Can't resolve qualified name for ChapterDao

### ISSUE THREAD

**Issue by fractalemagic** [greenrobot/greenDAO#368]
Edit: I've seen #352 and I have moved `apply plugin: 'org.greenrobot.greendao'` before `apply plugin: 'com.android.application'` but it *still doesn't work*

I'm using greenDAO 3 which fails when running the `greendao` Gradle task. I haven't used greenDAO 2 before, so I'm not in the process of upgrading.

Here's a sample project that can reproduce the error: https://github.com/fractalemagic/greendao3-error

The `greendao` task succeeds if I remove all of the class members annotated with `@Generated` and then run `./gradlew app:clean greendao`

```
Incremental java compilation is an incubating feature.
:app:clean
:app:greendaoPrepare
:app:greendao

BUILD SUCCESSFUL

Total time: 6.303 secs
```

However when the entity sources have been modified by greenDAO it fails. Here's the output when I run `./gradlew app:clean greendao --stacktrace`

```
:app:clean
:app:greendaoPrepare
:app:greendao FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:greendao'.
> Error processing "Chapter": Can't resolve qualified name for ChapterDao. Try to do not use imports on demand or specify qualified name explicitly (line 29)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:greendao'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:241)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:214)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:207)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: Error processing "Chapter": Can't resolve qualified name for ChapterDao. Try to do not use imports on demand or specify qualified name explicitly (line 29)
	at org.greenrobot.greendao.codemodifier.EntityClassASTVisitor.getTypeName(EntityClassASTVisitor.kt:70)
	at org.greenrobot.greendao.codemodifier.EntityClassASTVisitor.toVariableType(EntityClassASTVisitor.kt:63)
	at org.greenrobot.greendao.codemodifier.EntityClassASTVisitor.endVisit(EntityClassASTVisitor.kt:118)
	at org.eclipse.jdt.core.dom.FieldDeclaration.accept0(FieldDeclaration.java:291)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:212)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.greenrobot.greendao.codemodifier.EntityClassParser.parse(EntityClassParser.kt:33)
	at org.greenrobot.greendao.codemodifier.JdtCodeContext.parse(JdtCodeContext.kt:23)
	at org.greenrobot.greendao.codemodifier.Greendao3Generator$run$entities$1.invoke(Greendao3Generator.kt:28)
	at org.greenrobot.greendao.codemodifier.Greendao3Generator$run$entities$1.invoke(Greendao3Generator.kt:13)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:137)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:98)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:508)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:532)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:525)
	at org.greenrobot.greendao.codemodifier.Greendao3Generator.run(Greendao3Generator.kt:30)
	at org.greenrobot.greendao.gradle.Greendao3GradlePlugin$createGreendaoTask$$inlined$apply$lambda$1.execute(Greendao3GradlePlugin.kt:94)
	at org.greenrobot.greendao.gradle.Greendao3GradlePlugin$createGreendaoTask$$inlined$apply$lambda$1.execute(Greendao3GradlePlugin.kt:13)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 60 more
Caused by: java.lang.IllegalArgumentException: Can't resolve qualified name for ChapterDao. Try to do not use imports on demand or specify qualified name explicitly (line 29)
	at org.greenrobot.greendao.codemodifier.JdtUtilsKt.resolveName(JdtUtils.kt:63)
	at org.greenrobot.greendao.codemodifier.JdtUtilsKt.typeName(JdtUtils.kt:88)
	at org.greenrobot.greendao.codemodifier.EntityClassASTVisitor.getTypeName(EntityClassASTVisitor.kt:68)
	... 87 more


BUILD FAILED

Total time: 5.137 secs
```

**Comment by fractalemagic** [comment]
Oh... I should read the error messages properly next time. Sorry!

**Comment by samuelblattner** [comment]
I had trouble understanding @fractalemagic 's solution in IntelliJ at first until I figured out where my 'imports on demand' took place (sorry, had never heard of this term before... :-] ). In my specific case I had the following import in several of my model files:

`  import org.greenrobot.greendao.annotation.*;`

So I changed it into importing the specific classes like so:

```
import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.ToOne;
import org.greenrobot.greendao.annotation.Transient;
import org.greenrobot.greendao.annotation.ToMany;
import org.greenrobot.greendao.annotation.Generated;
```

And my app started working again.

**Comment by MFlisar** [comment]
This also happens without doing anything if you upgrade from v2 to v3, I had those `imports on demand` in all my generated entity classes...

**Comment by mharper** [comment]
I want _hours_ of my life back! 😂 Seriously, I agree with @samuelblattner and I should've read the error message verbatim and parsed it before going down the rabbit holes I did. Interestingly, the problem entity classes were those that had to-one and to-many relationships. Those that did not have such relationships compiled fine with:
```
import org.greenrobot.greendao.annotation.*;
```

**Comment by paveltech** [comment]
> 
> 
> I want _hours_ of my life back! 😂 Seriously, I agree with @samuelblattner and I should've read the error message verbatim and parsed it before going down the rabbit holes I did. Interestingly, the problem entity classes were those that had to-one and to-many relationships. Those that did not have such relationships compiled fine with:
> 
> ```
> import org.greenrobot.greendao.annotation.*;
> ```

where i should paste this code?
