### ISSUE TITLE
  I use the Green Dao. For SQLiteDiskIOException: disk I/O error, I need help.

### ISSUE THREAD

**Issue by maoaixianyu** [greenrobot/greenDAO#410]
In my application, I met this problem.  I use the Green Dao manager my database. For this problem, it effects my users. I need help, Please.
Fatal Exception: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 778)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
       at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
       at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
       at de.greenrobot.dao.AbstractDao.executeInsert(AbstractDao.java:352)
       at de.greenrobot.dao.AbstractDao.insertOrReplace(AbstractDao.java:332)
       at com.boxfish.stu.database.service.WordService.insertOrReplace(WordService.java:61)

**Comment by greenrobot-team** [comment]
This is an issue with your database. You probably should [search for the SQLite error code](http://lmgtfy.com/?q=sqlite+error+code+778).
