### ISSUE TITLE
Property 'xxx_xxx' is not part of xxxxDao

### ISSUE THREAD

**Issue by alejogamboa** [greenrobot/greenDAO#420]
Hi:
Using the greendao version 3.0.1 I'm getting this error:

```
org.greenrobot.greendao.DaoException: Property 'objectId' is not part of com.mimascotaap.model.to.local.ProductoDao@44a54a98
     at org.greenrobot.greendao.query.WhereCollector.checkProperty(WhereCollector.java:88)
     at org.greenrobot.greendao.query.WhereCollector.checkCondition(WhereCollector.java:73)
     at org.greenrobot.greendao.query.WhereCollector.add(WhereCollector.java:40)
     at org.greenrobot.greendao.query.Join.where(Join.java:52)
```

I'm trying to make a Join between two tables. and I'm pretty sure that 'objectId' its part of Producto and generated class. I'm wondering if this has something to deal with this past post:

https://github.com/greenrobot/greenDAO/issues/216

Thanks in advance

**Comment by greenrobot-team** [comment]
Well, did you check what was suggested in #216 and #344? (Are you using some kind of mocking tool or multidex?). -ut

**Comment by greenrobot-team** [comment]
No response. Closing.- ut
