### ISSUE TITLE
insertOrReplace not work well

### ISSUE THREAD

**Issue by chenzj-king** [greenrobot/greenDAO#437]
As title.

I update the version to 3.1.1. But when I insert it will crash and tell me like this  

	09-08 09:49:54.130 22583-22583/com.dreamliner.greendaosample E/AndroidRuntime: FATAL EXCEPTION: main
	                                                                               Process: com.dreamliner.greendaosample, PID: 22583
	                                                                               android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: Note._id(Sqlite code 1555),(OS error - 2:No such file or directory)
	                                                                                   at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	                                                                                   at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
	                                                                                   at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
	                                                                                   at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	                                                                                   at org.greenrobot.greendao.AbstractDao.insertInsideTx(AbstractDao.java:368)
	                                                                                   at org.greenrobot.greendao.AbstractDao.executeInsert(AbstractDao.java:351)
	                                                                                   at org.greenrobot.greendao.AbstractDao.insert(AbstractDao.java:319)
	                                                                                   at com.dreamliner.greendaosample.ui.activity.main.MainActivity.onClick(MainActivity.java:65)
	                                                                                   at com.dreamliner.greendaosample.ui.activity.main.MainActivity_ViewBinding$1.doClick(MainActivity_ViewBinding.java:39)
	                                                                                   at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
	                                                                                   at android.view.View.performClick(View.java:4768)
	                                                                                   at android.view.View$PerformClick.run(View.java:19692)
	                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
	                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
	                                                                                   at android.os.Looper.loop(Looper.java:135)
	                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5539)
	                                                                                   at java.lang.reflect.Method.invoke(Native Method)
	                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
	                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 

so i try to use insertOrReplace to do this job. And set id
autoincrment.

	@Entity(active = true, nameInDb = "Note")
	public class Note implements Serializable {
	
	    private static final long serialVersionUID = -1646980853280406016L;
	
	    @Id(autoincrement = true)
	    private long id;

	}

I just replace the defalut id=0 item. But it can't insert the new one.

Can you guide me to handle this problem. Thanks.

**Comment by chenzj-king** [comment]
I try to do like this. But It not good for me.

            Note note = new Note();

            List<Note> oldNotes = mNoteDao.queryBuilder().orderDesc(NoteDao.Properties.Id).limit(1).list();
            if (isNotNull(oldNotes)) {
                note.setId(oldNotes.get(0).getId() + 1);
            } else {
                note.setId(0);
            }
            note.setContent(mInputStr);

            mNoteDao.insertOrReplace(note);

**Comment by greenrobot-team** [comment]
Your log includes `(OS error - 2:No such file or directory)`, are you sure the database file exists and is writable?

Also you might want to use
```java
    @Id(autoincrement = true)
    private Long id;
```
and not set an `id` when inserting (so `id == null`).
 -ut

**Comment by chenzj-king** [comment]
I change long to Long for id. It work well. Thanks.
