### ISSUE TITLE
com.android.tools.build:gradle:2.2.0-rc1 not support

### ISSUE THREAD

**Issue by chufuxi** [greenrobot/greenDAO#442]
Cannot use latest build tool. Using 2.1.3 is ok.

gradlew greendao log

`Caused by: java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>([Lorg/eclipse/jdt/internal/compiler/batch/FileSystem$Classpath;[Ljava/lang/String;)V
        at org.eclipse.jdt.core.dom.NameEnvironmentWithProgress.<init>(NameEnvironmentWithProgress.java:29)
        at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:670)
        at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1183)
        at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:809)
        at org.greenrobot.greendao.codemodifier.EntityClassParser.parse(EntityClassParser.kt:24)
        at org.greenrobot.greendao.codemodifier.JdtCodeContext.parse(JdtCodeContext.kt:23)
        at org.greenrobot.greendao.codemodifier.Greendao3Generator$run$entities$1.invoke(Greendao3Generator.kt:29)
        at org.greenrobot.greendao.codemodifier.Greendao3Generator$run$entities$1.invoke(Greendao3Generator.kt:13)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:137)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:98)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:508)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:532)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:525)
        at org.greenrobot.greendao.codemodifier.Greendao3Generator.run(Greendao3Generator.kt:38)
        at org.greenrobot.greendao.gradle.Greendao3GradlePlugin$createGreendaoTask$$inlined$apply$lambda$1.execute(Greendao3GradlePlugin.kt:103)
        at org.greenrobot.greendao.gradle.Greendao3GradlePlugin$createGreendaoTask$$inlined$apply$lambda$1.execute(Greendao3GradlePlugin.kt:14)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more
`

**Comment by greenrobot-team** [comment]
Looks like a bug in the Android Gradle plugin. However, this version of the Android Gradle Plugin is still in development. Please re-file this bug if this problem still exists with the final 2.2.0 release of the Android Gradle Plugin. -ut

**Comment by dmascord** [comment]
Hi guys,

This issue still exists on the stable release of 2.2.0 of Android Gradle Plugin.

Caused by: java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>([Lorg/eclipse/jdt/internal/compiler/batch/FileS
ystem$Classpath;[Ljava/lang/String;)V
        at org.eclipse.jdt.core.dom.NameEnvironmentWithProgress.<init>(NameEnvironmentWithProgress.java:29)
        at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:670)
        at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1183)
        at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:809)
        at org.greenrobot.greendao.codemodifier.EntityClassParser.parse(EntityClassParser.kt:24)


Cheers,

Damien

**Comment by greenrobot-team** [comment]
Alright, looks like for some reason the integrated JDT Core version has changed. The constructor in question has changed [with this commit](http://git.eclipse.org/c/jdt/eclipse.jdt.core.git/commit/org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/NameEnvironmentWithProgress.java?id=e8a92b10517fc0e6b59559ac009096fb50176b96) from 2015-02-21.

[Associated Eclipse bug 440687](https://bugs.eclipse.org/bugs/show_bug.cgi?id=440687).

We will likely have to update our Eclipse JDT Core dependency. Still unsure about the version (according to the ticket it was release `4.4`).
-ut

**Comment by dmascord** [comment]
Looks like version 4.5 has that constructor, but 4.4 doesn't - http://git.eclipse.org/c/jdt/eclipse.jdt.core.git/tree/org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/NameEnvironmentWithProgress.java?h=R4_5_maintenance

**Comment by greenrobot-team** [comment]
Alright, looks like I found a good version. Using `org.eclipse.scout.sdk.deps:org.eclipse.jdt.core:3.11.0.v20150602-1242` packaged by the Eclipse Scout project. This will likely ship with greenDAO `3.2.0`.

However, once this is released the minimum supported Android Plugin version will be `2.2.0`. Using a lower version leads to the same conflict due to the different packaged JDT version.
-ut

**Comment by greenrobot-team** [comment]
Note: a temporary workaround is to include the plugin (`classpath 'org.greenrobot:greendao-gradle-plugin:3.1.1'`) in your root `build.gradle` file. -ut

**Comment by huayicheng2015** [comment]
**It does not work**

**Comment by dmascord** [comment]
What does not work?   Are you using 3.2.0, and have it configured as per installation instructions?

We are using 3.2.0 in our project, with much success.

**Comment by huayicheng2015** [comment]
It causes **#453**.
