### ISSUE TITLE
net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here

### ISSUE THREAD

**Issue by SyllaJay** [greenrobot/greenDAO#454]
I got “net.sqlcipher.database.DatabaseObjectNotClosedException” frequently. Refer to http://greenrobot.org/greendao/documentation/database-encryption/
Anyone can help please?

Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: INSERT OR REPLACE INTO "Session" ("_id","SESSION_KEY","TALK_ID","CREATED","UPDATED","COLOR","LAST_VI
net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
at net.sqlcipher.database.SQLiteCompiledSql.(SQLiteCompiledSql.java:62)
at net.sqlcipher.database.SQLiteProgram.(SQLiteProgram.java:103)
at net.sqlcipher.database.SQLiteStatement.(SQLiteStatement.java:39)
at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1556)
at de.greenrobot.dao.database.EncryptedDatabase.compileStatement(EncryptedDatabase.java:66)
at de.greenrobot.dao.internal.TableStatements.getInsertOrReplaceStatement(TableStatements.java:67)
at de.greenrobot.dao.AbstractDao.insertOrReplace(AbstractDao.java:335)
..... Our code just call insertOrReplace ......

**Comment by SyllaJay** [comment]
Code snippet:
ps: openHelper is instance of "de.greenrobot.dao.database.EncryptedDatabaseOpenHelper"

public void batchInsertOrUpdateSession(List entityList) {
Database db = openHelper.getWritableDatabase(mKey);
DaoMaster daoMaster = new DaoMaster(db);
DaoSession daoSession = daoMaster.newSession();
SessionDao dao = daoSession.getSessionDao();
dao.insertOrReplaceInTx(entityList);
}

**Comment by greenrobot-team** [comment]
The only thing I can think off: you should create the database, `DaoMaster` and `DaoSession` only once. For example in your `Application` class. greenDAO does not appear to `.close()` statements after it is done with them.

See [the example project](https://github.com/greenrobot/greenDAO/blob/V3.1.1/examples/DaoExample/src/main/java/org/greenrobot/greendao/example/App.java).
-ut

**Comment by SyllaJay** [comment]
@greenrobot-team Thanks very much! Where can I get the source code of "greendao-encryption 2.2.2"?

**Comment by greenrobot-team** [comment]
The `greendao-encryption` branch was experimental and was removed. With greenDAO 3.x encryption support is now part of the regular release. -ut

**Comment by ehunmayh** [comment]
Finalizing a Cursor that has not been deactivated or closed. database = /data/user/0/com.suirui.zhumu/databases/zhumu-db, table = null, query = SELECT p.CONTACT_ID, p.USER_NAME, p.HEAD_IMG_URL , a.ORG_ID FROM ORGANIZATION_CONTACT_INFO  a LEFT J
    net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
        at net.sqlcipher.database.SQLiteCursor.<init>(SQLiteCursor.java:226)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:71)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1867)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1785)
        at org.greenrobot.greendao.database.EncryptedDatabase.rawQuery(EncryptedDatabase.java:32)
        at com.suirui.zhumu.common.DBManager.getAllPersonsByOrgId(DBManager.java:443)
        at com.suirui.zhumu.contact.activity.SelectContactActivity.dealSelectAll(SelectContactActivity.java:588)
        at com.suirui.zhumu.contact.activity.SelectContactActivity.getData(SelectContactActivity.java:312)
        at com.suirui.zhumu.contact.activity.SelectContactActivity.lambda$refreshUI$53(SelectContactActivity.java:171)
        at com.suirui.zhumu.contact.activity.-$$Lambda$SelectContactActivity$3nCYf0rVaXrd5QGNt8oJ3hSwoGE.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by ehunmayh** [comment]
请问怎么解决的呀

**Comment by ehunmayh** [comment]
同样的调用一个方法偶现的出现这个异常

**Comment by greenrobot-team** [comment]
@ehunmayh 

`org.greenrobot.greendao.database.EncryptedDatabase.rawQuery(EncryptedDatabase.java:32)`

It looks like you are doing a raw query. Make sure to close the `Cursor` after you are done with it.
