### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference

### ISSUE THREAD

**Issue by BigSnake1989** [greenrobot/greenDAO#456]
RecordBean.java
```java
@Entity(active = true,nameInDb = "table_record")
public class RecordBean implements Serializable {

    @Id(autoincrement = true)
    @Property(nameInDb = "id")
    private Long id;    

    @Property(nameInDb = "type")
    private String type;
    ......
    ......
}
```

RecordBeanDao.java
```java
public class RecordBeanDao extends AbstractDao<RecordBean, Long> {

    public static final String TABLENAME = "table_record";

public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property Type = new Property(1, String.class, "type", false, "type");
        ......  
    };

public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"table_record\" (" + //
                "\"id\" INTEGER PRIMARY KEY AUTOINCREMENT," + // 0: id
                "\"type\" TEXT," + // 1: type
                "\"electronicsId\" TEXT," + // 2: electronicsId
                "\"name\" TEXT," + // 3: name
                "\"telephone\" TEXT," + // 4: telephone
                "\"identityNO\" TEXT," + // 5: identityNO
                "\"cardNO\" TEXT," + // 6: cardNO
                "\"registeredId\" TEXT," + // 7: registeredId
                "\"registered\" TEXT," + // 8: registered
                "\"fp_1\" TEXT," + // 9: fp_1
                "\"fp_2\" TEXT," + // 10: fp_2
                "\"imie\" TEXT," + // 11: imie
                "\"sex\" TEXT," + // 12: sex
                "\"isEntry\" INTEGER NOT NULL );"); // 13: isEntry
    }

@Override
    protected final void bindValues(DatabaseStatement stmt, RecordBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        ......
    }
}
```

```

lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
at net.hzlj.fp.greendao.RecordBeanDao.bindValues(RecordBeanDao.java:157)
at net.hzlj.fp.greendao.RecordBeanDao.bindValues(RecordBeanDao.java:19)
```

**Comment by BigSnake1989** [comment]
RecordBean{id=null, type='null', electronicsId='22877', name='测试456'}
`

**Comment by greenrobot-team** [comment]
Did you override/modify the `bindValues` method? By default it has a null check before binding the long value:

```java
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
```

Can you share your `bindValues` method? -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by umair-tp** [comment]
I had the exact same issue. I initialized the `id` with `1` and issue appears to be resolved.

Something like this :

    @Entity(active = true,nameInDb = "table_record")
    public class RecordBean implements Serializable  {

        @Id(autoincrement = true)
        @Property(nameInDb = "id")

       private Long id = 1;
        @Property(nameInDb = "type")
        private String type;
        ......
        ......
    }

Thought of adding this here, because maybe someday it may help someone in need (as me).

**Comment by indraAsLesmana** [comment]
same issue!.. get NPE from autoincrement.
