### ISSUE TITLE
  Pb(96) The serializable class does not declare a static final serialVersionUID field of type long (536871008 at line 14

### ISSUE THREAD

**Issue by followztx** [greenrobot/greenDAO#494]
upgrade to 3.2.0, it happen.

`* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:greendao'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: Found 1 problem(s) parsing 
Pb(96) The serializable class does not declare a static final serialVersionUID field of type long (536871008 at line 14
Run gradle with --info for more details
	at org.greenrobot.greendao.codemodifier.EntityClassParser.parse(EntityClassParser.kt:50)
	at org.greenrobot.greendao.codemodifier.JdtCodeContext.parse(JdtCodeContext.kt:23)
	at org.greenrobot.greendao.codemodifier.Greendao3Generator$run$entities$1.invoke(Greendao3Generator.kt:29)
	at org.greenrobot.greendao.codemodifier.Greendao3Generator$run$entities$1.invoke(Greendao3Generator.kt:13)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:137)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:98)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:536)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:560)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:553)
	at org.greenrobot.greendao.codemodifier.Greendao3Generator.run(Greendao3Generator.kt:38)
	at org.greenrobot.greendao.gradle.Greendao3GradlePlugin$createGreendaoTask$$inlined$apply$lambda$1.execute(Greendao3GradlePlugin.kt:103)
	at org.greenrobot.greendao.gradle.Greendao3GradlePlugin$createGreendaoTask$$inlined$apply$lambda$1.execute(Greendao3GradlePlugin.kt:14)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more`

**Comment by greenrobot-team** [comment]
Make sure to declare a field like:
```java
ANY-ACCESS-MODIFIER static final long serialVersionUID = 42L;
```
-ut

**Comment by Bertkiing** [comment]
please show me in details

**Comment by juan-castano** [comment]
This only work using `long` like primitive variable, it doesn't work `Long` like object variable.

**Comment by liutiantian** [comment]
i think this issue should be reopened, since it should never be the greendao's duty to guarantee that a class implements  Serializable should do anything particularly. and in current times, most classes use Serializable only as a signal to tell proguard logic not to obscure this class.
