### ISSUE TITLE
java.lang.NoClassDefFoundError: org.greenrobot.greendao.database.StandardDatabase

### ISSUE THREAD

**Issue by rashid-1234** [greenrobot/greenDAO#510]
I am having a problem in Samsung S3 phone (API level 16). I am getting the crash at the run time on database creation. Below is the stacktrace for this crash. Kindly let me know the suggestion for this. Please respond soon because I am in the process of selecting good android ORM. So it will help in that.

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   java.lang.NoClassDefFoundError: org.greenrobot.greendao.database.StandardDatabase
                                                                       at org.greenrobot.greendao.database.DatabaseOpenHelper.wrap(DatabaseOpenHelper.java:71)
                                                                       at org.greenrobot.greendao.database.DatabaseOpenHelper.onCreate(DatabaseOpenHelper.java:79)
                                                                       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
                                                                       at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
                                                                       at com.esealed.dchat.App.initDB2(App.java:64)
                                                                       at com.esealed.dchat.App.onCreate(App.java:44)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1003)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4228)
                                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:140)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:4898)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by greenrobot-team** [comment]
This is likely an issue with ProGuard stripping this class. [See the FAQ](http://greenrobot.org/greendao/documentation/technical-faq/) for the rules to add to your ProGuard rules file for greenDAO. -ut

**Comment by rashid-1234** [comment]
But i am not using this in release mode. How the ProGuard stripping this class in debug mode?

**Comment by greenrobot-team** [comment]
Double-[check your gradle config file](https://developer.android.com/studio/build/shrink-code.html#shrink-code), you can also look in the `build` folder for a `usage.txt` for your build variant. Just for experimentation, try to add the rules and see if it works.

Also, if you are using it, you might have to disable multidex.

Here is [some general help on NoClassDefFoundError](http://stackoverflow.com/a/17974068).
-ut

**Comment by rashid-1234** [comment]
I checked again it is not a release mode. What more information should I provide to you to find the problem..

**Comment by rashid-1234** [comment]
It was not a issue of GreenDAO  but a multidex issue  Ref: http://stackoverflow.com/questions/26609734/how-to-enable-multidexing-with-the-new-android-multidex-support-library

GreenDAO is working perfect.
