### ISSUE TITLE
Annotation Id dont work

### ISSUE THREAD

**Issue by Gvardia** [greenrobot/greenDAO#620]
```
E/MinderType ID: id = 1
E/AndroidRuntime: FATAL EXCEPTION: main
Process: , PID: 21263
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6126)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
 Caused by: java.lang.UnsupportedOperationException: Unsupported for entities with a non-null key
    at com.tangosquared.petminder.database.greendao.MinderTypeDao.hasKey(MinderTypeDao.java:160)
    at com.tangosquared.petminder.database.greendao.MinderTypeDao.hasKey(MinderTypeDao.java:18)
    at org.greenrobot.greendao.AbstractDao.save(AbstractDao.java:394)
    at com.tangosquared.petminder.repository.MinderTypeRepository.saveAll(MinderTypeRepository.java:24)
    at com.tangosquared.petminder.minder.minder_type.MinderTypeModel$3.onNext(MinderTypeModel.java:82)
    at com.tangosquared.petminder.minder.minder_type.MinderTypeModel$3.onNext(MinderTypeModel.java:72)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
    at android.os.Handler.handleCallback(Handler.java:751) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6126) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

```
@Entity
public class MinderType {

    @Id
    @Unique
    private long id;

    @Expose
    @SerializedName("name")
    private String name;

    @Expose
    @SerializedName("title")
    private String title;

    @Expose
    @SerializedName("color")
    private String color;

    @Expose
    @SerializedName("alias")
    private String alias;

    @Expose
    @SerializedName("is_custom")
    private boolean isCustom;
```

Why?

**Comment by greenrobot-team** [comment]
Using `dao.save()` is only possible if you are using `Long` (a nullable type) for your entity ID. Like:

```
    @Id
    private Long id;
```

Why? Based on the key being `null` greenDAO determines whether it should insert or update the entity when calling `save()`.

Also note that `@Id` already implies that it has to be `@Unique`, so it can be removed. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
