### ISSUE TITLE
java.lang.NoSuchFieldException: TABLENAME

### ISSUE THREAD

**Issue by umesh0492** [greenrobot/greenDAO#630]
java.lang.RuntimeException: Unable to create application com.frainz.android.MainApplication: org.greenrobot.greendao.DaoException: Could not init DAOConfig
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4569)
    at android.app.ActivityThread.access$1300(ActivityThread.java:156)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:153)
    at android.app.ActivityThread.main(ActivityThread.java:5297)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
    at dalvik.system.NativeStart.main(NativeStart.java)
org.greenrobot.greendao.DaoException: Could not init DAOConfig
    at org.greenrobot.greendao.c.a.<init>(DaoConfig.java:94)
    at org.greenrobot.greendao.b.G(AbstractDaoMaster.java:44)
    at com.frainz.android.data.db.model.h.<init>(DaoMaster.java:62)
    at com.frainz.android.data.db.a.<init>(AppDbHelper.java:93)
    at com.frainz.android.data.db.d.Aj(AppDbHelper_Factory.java:29)
    at com.frainz.android.data.db.d.get(AppDbHelper_Factory.java:9)
    at a.a.a.get(DoubleCheck.java:47)
    at com.frainz.android.a.b.ac.CE(ApplicationModule_ProvideDbHelperFactory.java:30)
    at com.frainz.android.a.b.ac.get(ApplicationModule_ProvideDbHelperFactory.java:10)
    at a.a.a.get(DoubleCheck.java:47)
    at com.frainz.android.data.b.Ag(AppDataManager_Factory.java:43)
    at com.frainz.android.data.b.get(AppDataManager_Factory.java:11)
    at a.a.a.get(DoubleCheck.java:47)
    at com.frainz.android.a.b.aa.BS(ApplicationModule_ProvideDataManagerFactory.java:30)
    at com.frainz.android.a.b.aa.get(ApplicationModule_ProvideDataManagerFactory.java:10)
    at a.a.a.get(DoubleCheck.java:47)
    at com.frainz.android.b.a(MainApplication_MembersInjector.java:38)
    at com.frainz.android.b.bt(MainApplication_MembersInjector.java:9)
    at com.frainz.android.a.a.d.b(DaggerApplicationComponent.java:181)
    at com.frainz.android.MainApplication.onCreate(MainApplication.java:105)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4566)
    at android.app.ActivityThread.access$1300(ActivityThread.java:156)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:153)
    at android.app.ActivityThread.main(ActivityThread.java:5297)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
    at dalvik.system.NativeStart.main(NativeStart.java)
java.lang.NoSuchFieldException: TABLENAME
    at java.lang.Class.getField(Class.java:787)
    at org.greenrobot.greendao.c.a.<init>(DaoConfig.java:56)
    at org.greenrobot.greendao.b.G(AbstractDaoMaster.java:44)
    at com.frainz.android.data.db.model.h.<init>(DaoMaster.java:62)
    at com.frainz.android.data.db.a.<init>(AppDbHelper.java:93)
    at com.frainz.android.data.db.d.Aj(AppDbHelper_Factory.java:29)
    at com.frainz.android.data.db.d.get(AppDbHelper_Factory.java:9)
    at a.a.a.get(DoubleCheck.java:47)
    at com.frainz.android.a.b.ac.CE(ApplicationModule_ProvideDbHelperFactory.java:30)
    at com.frainz.android.a.b.ac.get(ApplicationModule_ProvideDbHelperFactory.java:10)
    at a.a.a.get(DoubleCheck.java:47)
    at com.frainz.android.data.b.Ag(AppDataManager_Factory.java:43)
    at com.frainz.android.data.b.get(AppDataManager_Factory.java:11)
    at a.a.a.get(DoubleCheck.java:47)
    at com.frainz.android.a.b.aa.BS(ApplicationModule_ProvideDataManagerFactory.java:30)
    at com.frainz.android.a.b.aa.get(ApplicationModule_ProvideDataManagerFactory.java:10)
    at a.a.a.get(DoubleCheck.java:47)
    at com.frainz.android.b.a(MainApplication_MembersInjector.java:38)
    at com.frainz.android.b.bt(MainApplication_MembersInjector.java:9)
    at com.frainz.android.a.a.d.b(DaggerApplicationComponent.java:181)
    at com.frainz.android.MainApplication.onCreate(MainApplication.java:105)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4566)
    at android.app.ActivityThread.access$1300(ActivityThread.java:156)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:153)
    at android.app.ActivityThread.main(ActivityThread.java:5297)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
    at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by umesh0492** [comment]
proguard

-keepclassmembers class * extends org.greenrobot.dao.AbstractDao {
public static final java.lang.String TABLENAME;
}
-keep class **$Properties

# If you do not use SQLCipher:
-dontwarn org.greenrobot.greendao.database.**
# If you do not use RxJava:
-dontwarn rx.**
