### ISSUE TITLE
table HISTORY_VIDEO has no column named _id

### ISSUE THREAD

**Issue by weituotian** [greenrobot/greenDAO#634]
why it will be `_id`, i defind `id` in my entity
```
 Caused by: rx.exceptions.OnErrorNotImplementedException: table HISTORY_VIDEO has no column named _id: , while compiling: INSERT INTO "HISTORY_VIDEO" ("_id","COVER","TITLE","DESCRIPT","CLICK","PLAY","COLLECT","MEMBER_NAME","PARTITION_NAME","CREATE_TIME","TOTAL_TIME","VIEW_TIME") VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
                      at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
                      at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
                      at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                      at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
                      at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
```

and my entity:
```java
@Entity
public class HistoryVideo {

    @Id
    private long id;

    private String cover;

    private String title;

    private String descript;

    private Integer click;

    private Integer play;

    private Integer collect;

    private String memberName;

    private String partitionName;

    private Date createTime;

    private Integer totalTime;

    //观看此视频的时间
    private Date viewTime;

    @Generated(hash = 1255627282)
    public HistoryVideo(long id, String cover, String title, String descript,
            Integer click, Integer play, Integer collect, String memberName,
            String partitionName, Date createTime, Integer totalTime,
            Date viewTime) {
        this.id = id;
        this.cover = cover;
        this.title = title;
        this.descript = descript;
        this.click = click;
        this.play = play;
        this.collect = collect;
        this.memberName = memberName;
        this.partitionName = partitionName;
        this.createTime = createTime;
        this.totalTime = totalTime;
        this.viewTime = viewTime;
    }

    @Generated(hash = 717473908)
    public HistoryVideo() {
    }
    
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    public String getMemberName() {
        return memberName;
    }

    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    public String getPartitionName() {
        return partitionName;
    }

    public void setPartitionName(String partitionName) {
        this.partitionName = partitionName;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getClick() {
        return click;
    }

    public void setClick(Integer click) {
        this.click = click;
    }

    public Integer getPlay() {
        return play;
    }

    public void setPlay(Integer play) {
        this.play = play;
    }

    public Integer getCollect() {
        return collect;
    }

    public void setCollect(Integer collect) {
        this.collect = collect;
    }

    public String getDescript() {
        return descript;
    }

    public void setDescript(String descript) {
        this.descript = descript;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Integer getTotalTime() {
        return totalTime;
    }

    public void setTotalTime(Integer totalTime) {
        this.totalTime = totalTime;
    }

    public Date getViewTime() {
        return viewTime;
    }

    public void setViewTime(Date viewTime) {
        this.viewTime = viewTime;
    }
}
```

**Comment by greenrobot-team** [comment]
Your entity looks fine.

Are you using a custom open helper for your database? Check that it calls `createAllTables()` of `DaoMaster`. 

Otherwise I can not reproduce this without an example project.
-ut

**Comment by weituotian** [comment]
@greenrobot-team 
it  is all fine now, becaues

before:
```
ENCRYPTED=true;
DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper(this, ENCRYPTED ? "notes-db-encrypted" : "notes-db");
        Database db = ENCRYPTED ? helper.getEncryptedWritableDb("super-secret") : helper.getWritableDb();
        daoSession = new DaoMaster(db).newSession();
```

after:
```
        File path = new File(Environment.getExternalStorageDirectory(), "weituotian/video-db");
        path.getParentFile().mkdirs();

        DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper(this, path.getAbsolutePath(), null);
        Database db = helper.getWritableDb();

        daoSession = new DaoMaster(db).newSession();
```
when i do not use EncryptedWritableDb,
i insert success
![image](https://cloud.githubusercontent.com/assets/7270968/24599431/c1bfa668-1882-11e7-8a0a-545a3ee12ab4.png)

compare the two ways.
Probably it is the problem with sqlchiper
i just add the sqlcipher,
and have no config of it
```
    //greendao
    compile 'net.zetetic:android-database-sqlcipher:3.5.6@aar'
    compile 'org.greenrobot:greendao:3.2.0'
```


is there be some configration code about sqlcipher, 
or i can not insert into the table
