### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by nuli1228588792** [greenrobot/greenDAO#650]
04-15 09:39:11.568 1078-1078/com.letdb E/AndroidRuntime: FATAL EXCEPTION: main
                                                         java.lang.NoClassDefFoundError: org.greenrobot.greendao.database.StandardDatabase
                                                             at org.greenrobot.greendao.database.DatabaseOpenHelper.wrap(DatabaseOpenHelper.java:71)
                                                             at org.greenrobot.greendao.database.DatabaseOpenHelper.onOpen(DatabaseOpenHelper.java:109)
                                                             at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:267)
                                                             at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
                                                             at org.greenrobot.greendao.database.DatabaseOpenHelper.getWritableDb(DatabaseOpenHelper.java:59)
                                                             at com.letdb.app.MyApp.initDaoSession(MyApp.java:218)
                                                             at com.letdb.app.MyApp.onCreate(MyApp.java:98)
                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4440)
                                                             at android.app.ActivityThread.access$1300(ActivityThread.java:144)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
                                                             at android.os.Handler.dispatchMessage(Handler.java:99)
                                                             at android.os.Looper.loop(Looper.java:137)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5090)
                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                             at dalvik.system.NativeStart.main(Native Method)

this error how  can I issue it ?

**Comment by greenrobot-team** [comment]
[My comment](https://github.com/greenrobot/greenDAO/issues/651#issuecomment-297006936) on #651 applies. -ut
