### ISSUE TITLE
java.lang.NoClassDefFoundError: org.greenrobot.greendao.query.QueryBuilder

### ISSUE THREAD

**Issue by nuli1228588792** [greenrobot/greenDAO#651]
and this when I run my device it throw RuntimeExcepition like that ,then my app was corrupted.
I use studio 2.3.1。  please help me ! 

04-15 09:50:36.936 10710-10710/com.letdb E/AndroidRuntime: FATAL EXCEPTION: main
                                                           java.lang.NoClassDefFoundError: org.greenrobot.greendao.query.QueryBuilder
                                                               at org.greenrobot.greendao.AbstractDao.queryBuilder(AbstractDao.java:793)
                                                               at com.letdb.ui.SearchActivity.initLatestSearch(SearchActivity.java:286)
                                                               at com.letdb.ui.SearchActivity.onCreate(SearchActivity.java:111)
                                                               at android.app.Activity.performCreate(Activity.java:5214)
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2147)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                               at android.app.ActivityThread.access$600(ActivityThread.java:144)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                               at android.os.Looper.loop(Looper.java:137)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5090)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:511)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                               at dalvik.system.NativeStart.main(Native Method)

**Comment by greenrobot-team** [comment]
This looks like a ProGuard or multidex issue. Check your configuration files. Otherwise I can't help without an example project. -ut

**Comment by Vicent9920** [comment]
我的项目也遇到类似的问题了：
`java.lang.NoClassDefFoundError: org.greenrobot.greendao.query.WhereCollector
at org.greenrobot.greendao.query.QueryBuilder.<init>(QueryBuilder.java:85)
                                                                                         at org.greenrobot.greendao.query.QueryBuilder.<init>(QueryBuilder.java:77)
                                                                                         at org.greenrobot.greendao.query.QueryBuilder.internalCreate(QueryBuilder.java:73)
                                                                                         at org.greenrobot.greendao.AbstractDao.queryBuilder(AbstractDao.java:793)
                                                                                         at com.luckytry.luckylibrary.MyAplication.APPAplication.initData(APPAplication.java:132)
                                                                                         at com.luckytry.luckylibrary.MyAplication.APPAplication.initDB(APPAplication.java:117)
                                                                                         at com.luckytry.luckylibrary.MyAplication.APPAplication.onCreate(APPAplication.java:39)
                                                                                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009)
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4655)
                                                                                         at android.app.ActivityThread.access$1800(ActivityThread.java:143)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5356)
                                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                                         at dalvik.system.NativeStart.main(Native Method)`
AndroidStudio是2.3.之前关电脑重启解决过这个问题，但是这次前面的方法没有效果了。请问也没有什么有效的方法可以快速解决这个问题？

**Comment by nuli1228588792** [comment]
http://blog.csdn.net/pengkv/article/details/51177217 你看一下是不是jar包太多的原因

**Comment by Vicent9920** [comment]
[已经解决了](http://blog.csdn.net/Vicent_9920/article/details/71171434)

**Comment by greenrobot-team** [comment]
So closing this then. -ut
