### ISSUE TITLE
android.database.sqlite.SQLiteFullException: database or disk is full 

### ISSUE THREAD

**Issue by hljstardust** [greenrobot/greenDAO#655]
```
android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:569)
	at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:381)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:228)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:203)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:836)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:821)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1252)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:267)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at com.autohome.main.me.storage.greendao.THDevOpenHelper.getWritableDatabase(THDevOpenHelper.java:38)

```

**Comment by greenrobot-team** [comment]
Well, I guess the issue is `SQLiteFullException: database or disk is full (code 13)`. This is nothing specific to greenDAO, this is a common SQLite error code. Look it up online. -ut

**Comment by nickylin** [comment]
@hljstardust have u solved this problem, i also have this problem, i dont know this is no disk for real or i use the db in wrong way or wal mode use a lot of disk space?
