### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by umesh0492** [greenrobot/greenDAO#672]
java.lang.IllegalStateException: Couldn't read row 0, col 4 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetLong(CursorWindow.java)
    at android.database.CursorWindow.getLong(CursorWindow.java:507)
    at android.database.CursorWindow.getInt(CursorWindow.java:574)
    at org.greenrobot.greendao.c.b.getInt(FastCursor.java:167)
    at com.frainz.android.data.db.model.ChatRoomModelDao.readEntity(ChatRoomModelDao.java:270)
    at com.frainz.android.data.db.model.ChatRoomModelDao.readEntity(ChatRoomModelDao.java:19)
    at org.greenrobot.greendao.a.loadCurrent(AbstractDao.java:565)
    at org.greenrobot.greendao.a.loadAllFromCursor(AbstractDao.java:483)
    at org.greenrobot.greendao.a.loadAllAndCloseCursor(AbstractDao.java:203)
    at org.greenrobot.greendao.e.loadAllAndCloseCursor(InternalQueryDaoAccess.java:37)
    at org.greenrobot.greendao.d.g.YH(Query.java:89)
    at org.greenrobot.greendao.d.h.YH(QueryBuilder.java:427)

**Comment by greenrobot-team** [comment]
This is likely an issue with how you [insert or update entities](http://greenrobot.org/greendao/documentation/how-to-get-started/#Inserting_and_deleting_notes). Can you show us what code is leading to this error? -ut

**Comment by umesh0492** [comment]
mDaoSession.getChatRoomModelDao ()
                .queryBuilder ()
                .where (ChatRoomModelDao.Properties.Type.eq (Const.RoomType.PUBLIC.getType ()))
                .list ();

**Comment by umesh0492** [comment]
It's only happening, when DAO is accessed in Service class.

**Comment by greenrobot-team** [comment]
Is your service [running in a different process](https://developer.android.com/guide/topics/manifest/service-element.html#proc)? If yes, try not to.

Otherwise this might be an issue with `org.greenrobot.greendao.internal.FastCursor`, but I have very limited knowledge here. @greenrobot should know more. -ut

**Comment by umesh0492** [comment]
@greenrobot-team My service is not running in different process "as of now", but soon it would be. It's a requirement of product to go multiprocess and that service would go in different process.

@greenrobot can you tell me more what is this issue org.greenrobot.greendao.internal.FastCursor. Also why not to go multiprocess with GreenDao? or is there any other way that I can go multiprocess with GreenDao? 

Thanks :)
