### ISSUE TITLE
Migration Failed or Delayed (Handled on upgrade as stated in docs)

### ISSUE THREAD

**Issue by umesh0492** [greenrobot/greenDAO#675]
```
android.database.sqlite.SQLiteException: no such column: T.LAST_READ_MESSAGE_AT (code 1): , while compiling: SELECT T."ID",T."NAME",T."DESC",T."TYPE",T."USERS",T."MAX_USERS",T."OWNER",T."CREATED_ON",T."LAST_MESSAGE_AT",T."LAST_MESSAGE_ID",T."LAST_READ_MESSAGE_ID",T."LAST_READ_MESSAGE_AT",T."UPDATED_ON",T."PROMOTED",T."INVITE_CODE",T."INVITE_ACCESS",T."SUBSCRIBE_STATUS",T."JOIN_STATUS",T."TOTAL_ANNOUNCEMENTS",T."TOTAL_LIKES",T."UNREAD_MESSAGE_COUNT",T."MUTE_ALL",T."MUTE_MESSAGE",T."ROOM_IMAGE",T."LAST_MESSAGE" FROM "CHAT_ROOM_MODEL" T
    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
    at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
    at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
    at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
    at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
    at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
    at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
    at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
    at org.greenrobot.greendao.a.f.rawQuery(StandardDatabase.java:32)
    at org.greenrobot.greendao.d.g.Yc(Query.java:88)
    at org.greenrobot.greendao.d.h.Yc(QueryBuilder.java:427)
    at com.frainz.android.data.db.a.zB(AppDbHelper.java:1662)
    at com.frainz.android.data.a.zB(AppDataManager.java:438)
    at com.frainz.android.service.MessageService.aQ(MessageService.java:373)
    at com.frainz.android.service.MessageService.a(MessageService.java:91)
    at com.frainz.android.service.MessageService$2.a(MessageService.java:317)
  
```

**Comment by umesh0492** [comment]
Not happening with every device.

**Comment by greenrobot-team** [comment]
Have you implemented `onUpgrade()` in your `OpenHelper` implementation and added the new column?

Also, it looks like you are using ProGuard. Check that your rules match the ones [provided in the FAQ](http://greenrobot.org/greendao/documentation/technical-faq/).
 -ut

**Comment by greenrobot-team** [comment]
Update: There is [an example](https://github.com/greenrobot/greenDAO/issues/137#issuecomment-52026621) in #137. -ut

**Comment by umesh0492** [comment]
@greenrobot-team I have implemented "onUpgrade". I am using proguard and implemented it as per your documentation. Will have a look on #137 .
