### ISSUE TITLE
Error java.lang.NoClassDefFoundError on Android 4.4

### ISSUE THREAD

**Issue by alejogamboa** [greenrobot/greenDAO#681]

**Comment by alejogamboa** [comment]
Hello,

I recently posted an app on the playstore and I'm getting a lot of bug reports that happens when I call and instantiate a connection to the database. Specifically with these two lines:

DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper (this, Utils.DB_NAME, null);
Db = helper.getWritableDatabase ();

It only happens on android 4.4 devices. I research for this error and I find on your FAQ that there is a pro-issue issue. I add the suggested configuration and nothing hapens anyway. Please help. THe stack trace:

java.lang.NoClassDefFoundError: 
  at org.greenrobot.greendao.database.DatabaseOpenHelper.wrap(DatabaseOpenHelper.java:71)
  at org.greenrobot.greendao.database.DatabaseOpenHelper.onCreate(DatabaseOpenHelper.java:79)
  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
  at com.kaptarnosmueve.kaptar.App.iniciarBdLocal(App.java:71)
  at com.kaptarnosmueve.kaptar.App.onCreate(App.java:31)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4632)
  at android.app.ActivityThread.access$1800(ActivityThread.java:141)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5336)
  at java.lang.reflect.Method.invokeNative(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
  at dalvik.system.NativeStart.main(Native Method:0)

**Comment by greenrobot-team** [comment]
Looks like the crash is at [this line in DatabaseOpenHelper](https://github.com/greenrobot/greenDAO/blob/V3.2.2/DaoCore/src/main/java/org/greenrobot/greendao/database/DatabaseOpenHelper.java#L71). Make sure your final APK does not exclude the `org.greenrobot.greendao.database.StandardDatabase` class (check with for example the [APK analyzer in Android Studio](https://developer.android.com/studio/build/apk-analyzer.html)). -ut

**Comment by alejogamboa** [comment]
Hello GreenDao team. I check the APK as you suggest and actually the class is present. There are any other thing to check?

**Comment by greenrobot-team** [comment]
By any chance, are you using multidex (check your app `build.gradle` file)? If yes, [make sure that the greenDAO classes are in the primary dex file](https://developer.android.com/studio/build/multidex.html#keep) as it appears it is required for your app to start. Or turn off multidex if it is not required. -ut

**Comment by KevinDestinydoor** [comment]
I  faced  same  problem!

**Comment by KevinDestinydoor** [comment]
4-19 07:10:14.983 24631-24631/E/dalvikvm: Could not find class 'com.zgl.greentest.gen.DaoMaster$DevOpenHelper', referenced from method db.GreenDaoManager.<init>
04-19 07:10:15.021 24631-24631/E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.NoClassDefFoundError: com.zgl.greentest.gen.DaoMaster$DevOpenHelper
                                                                           at db.GreenDaoManager.<init>(GreenDaoManager.java:22)

**Comment by greenrobot-team** [comment]
@KevinDestinydoor [Same as before](https://github.com/greenrobot/greenDAO/issues/681#issuecomment-303299353), did you open the release APK in Android Studio and check if the `com.zgl.greentest.gen.DaoMaster$DevOpenHelper` class is actually in the APK? Your ProGuard configuration might exclude it, or your multidex configuration might not include it in the primary dex file. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
