### ISSUE TITLE
syntax error about SqlUtils.createSqlUpdate

### ISSUE THREAD

**Issue by Lesences** [greenrobot/greenDAO#693]
My code :
```java
long accountId = PrefrenceUtil.getInstance().getAccountId();
        String[] updateColumn = new String[]{"SHOW_POINT"};
        String[] whereColumns = new String[]{"SHOW_POINT", "ACCOUNT_ID"};
        String[] valueColumns = new String[]{"0", "1", String.valueOf(accountId)};
        String sql = SqlUtils.createSqlUpdate(DaoYunbaMsgModelDao.TABLENAME, updateColumn, whereColumns);
        dataBase.execSQL(sql, valueColumns);
```
Exception:

```java
  java.lang.RuntimeException:******: net.sqlcipher.database.SQLiteException: near ",": syntax error: , while compiling: UPDATE "DAO_YUNBA_MSG_MODEL" SET "SHOW_POINT"=? WHERE "DAO_YUNBA_MSG_MODEL"."SHOW_POINT"=?,"DAO_YUNBA_MSG_MODEL"."ACCOUNT_ID"=?
                                                                                     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3651)
                                                                                     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3669)
                                                                                     at android.app.ActivityThread.access$1400(ActivityThread.java:155)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5426)
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                                  Caused by: net.sqlcipher.database.SQLiteException: near ",": syntax error: , while compiling: UPDATE "DAO_YUNBA_MSG_MODEL" SET "SHOW_POINT"=? WHERE "DAO_YUNBA_MSG_MODEL"."SHOW_POINT"=?,"DAO_YUNBA_MSG_MODEL"."ACCOUNT_ID"=?
                                                                                     at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
                                                                                     at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
                                                                                     at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
                                                                                     at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
                                                                                     at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
                                                                                     at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1589)
                                                                                     at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2312)
                                                                                     at org.a.a.a.d.a(EncryptedDatabase.java:62)
```

I write a sql like

```java
String sql = "UPDATE DAO_YUNBA_MSG_MODEL SET SHOW_POINT=? WHERE DAO_YUNBA_MSG_MODEL.SHOW_POINT=? AND DAO_YUNBA_MSG_MODEL.ACCOUNT_ID=?";
```

" , " => " AND " , it will be running OK !

So ,  I think  it is a bug !

**Comment by Lesences** [comment]
I write a sql like
```java
String sql = "UPDATE DAO_YUNBA_MSG_MODEL SET SHOW_POINT=? WHERE DAO_YUNBA_MSG_MODEL.SHOW_POINT=? AND DAO_YUNBA_MSG_MODEL.ACCOUNT_ID=?";
```
" , " => " AND " it will be fun !

I think this is a bug !

**Comment by greenrobot-team** [comment]
`SqlUtils` is for internal use by greenDAO only. Do not use it in your own code.

To update entities query them from the database, modify some properties, then update them [using the `update()` method on the respective DAO class](http://greenrobot.org/greendao/documentation/how-to-get-started/#Updating_notes_and_more).
-ut
