### ISSUE TITLE
java.lang.NoClassDefFoundError: org.greenrobot.greendao.database.StandardDatabase

### ISSUE THREAD

**Issue by qqdongshao123** [greenrobot/greenDAO#694]
When I was using the GreenDao database, android5.0 didn't have any problems. Android4.4 was always wrong. What's the reason for this?
`Process: com.hlzx.dydp, PID: 8466
                                                             java.lang.NoClassDefFoundError: org.greenrobot.greendao.database.StandardDatabase
                                                                 at org.greenrobot.greendao.database.DatabaseOpenHelper.wrap(DatabaseOpenHelper.java:71)
                                                                 at org.greenrobot.greendao.database.DatabaseOpenHelper.onCreate(DatabaseOpenHelper.java:79)
                                                                 at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
                                                                 at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
                                                                 at com.hlzx.dydp.app.LePingApplication.setupDatabase(LePingApplication.java:222)
                                                                 at com.hlzx.dydp.app.LePingApplication.onCreate(LePingApplication.java:178)
                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4632)
                                                                 at android.app.ActivityThread.access$1800(ActivityThread.java:141)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5333)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
                                                                 at dalvik.system.NativeStart.main(Native Method)`

**Comment by qqdongshao123** [comment]
http://blog.csdn.net/u010151514/article/details/72865861

**Comment by greenrobot-team** [comment]
See [my comment](https://github.com/greenrobot/greenDAO/issues/681#issuecomment-307700741) on issue #681.
