### ISSUE TITLE
How to insert initial data when table has been created

### ISSUE THREAD

**Issue by black-lotus** [greenrobot/greenDAO#704]
[ASK] Is it possible to insert initial data after table has been created ?

I have followed this code but always getting error

```
DaoMaster.OpenHelper helper = new DaoMaster.OpenHelper(this, "nogeek-db") {
            @Override
            public void onCreate(Database db) {
                super.onCreate(db);
                Log.d("DAO_MASTER", "CREATE DB");

                // insert category
                db.execSQL("INSERT INTO category (category_id, category_name) VALUES(1, 'Blabla')");

                db.endTransaction();
            }
        }; //The users-db here is the name of our database.

        Database db = helper.getWritableDb();
        this.daoSession = new DaoMaster(db).newSession();
```

and this is the error i got

```
process: com.donny.nogeek, PID: 9918
                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.donny.nogeek/com.mygdx.game.android.activities.main.MainActivity}: android.database.sqlite.SQLiteException: no such table: CATEGORY (code 1): , while compiling: SELECT T."_id",T."CATEGORY_ID",T."CATEGORY_NAME" FROM "CATEGORY" T
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                 Caused by: android.database.sqlite.SQLiteException: no such table: CATEGORY (code 1): , while compiling: SELECT T."_id",T."CATEGORY_ID",T."CATEGORY_NAME" FROM "CATEGORY" T
                                                                    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                    at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                                    at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                    at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                    at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                    at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                    at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
                                                                    at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1257)
                                                                    at org.greenrobot.greendao.database.StandardDatabase.rawQuery(StandardDatabase.java:32)
                                                                    at org.greenrobot.greendao.AbstractDao.loadAll(AbstractDao.java:177)
                                                                    at com.mygdx.game.android.activities.main.MainActivity.onCreate(MainActivity.java:56)
                                                                    at android.app.Activity.performCreate(Activity.java:6662)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:154) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

Any help would be appreciated

**Comment by greenrobot-team** [comment]
The error indicates an issue with querying the table `CATEGORY` in your `MainActivity#onCreate()` (line 56) before it exists.

As for inserting values: Have a look at the `onCreate()` method of `DaoMaster.OpenHelper`. It should have a `DaoMaster#createAllTables()` method. There inspect the `createTable()` methods as to what tables with what names are actually created. Most likely the table name is different from what you are expecting (`CATEGORY`).

Tip: you can also get the table name for an entity using for example the `CategoryDao.TABLENAME` constant.

-ut

**Comment by black-lotus** [comment]
Hi @greenrobot-team 

I have ovveride OpenHelper

```
@Override
public void onCreate(Database db) {
   super.onCreate(db);
   Log.d("DAO_MASTER", "CREATE DB");
  
   // insert category
   db.execSQL("INSERT INTO category (category_id, category_name) VALUES(1, 'Blabla')");

   db.endTransaction();
 }
```

inside class OpenHelper, onCreate method
it's already call create tables or drop tables

and, when i remove `db.execSQL()` everything goes success

Thank you

**Comment by greenrobot-team** [comment]
I just tried to reproduce this using our ´Note` example. I created a custom ´OpenHelper` and it works just fine:

```java
public static class ExampleOpenHelper extends DaoMaster.OpenHelper {

    public ExampleOpenHelper(Context context, String name) {
        super(context, name);
    }

    @Override
    public void onCreate(Database db) {
        super.onCreate(db);

        db.execSQL("INSERT INTO " + NoteDao.TABLENAME + " (" +
                NoteDao.Properties.Id.columnName + ", " +
                NoteDao.Properties.Date.columnName + ", " +
                NoteDao.Properties.Text.columnName +
                ") VALUES(1, 0, 'Example Note')");
    }
}
```

Do you actually have a `CategoryDao`? What is the value of `CategoryDao.TABLENAME`?
-ut

**Comment by black-lotus** [comment]
it was hard coded
whoaa there is property "NoteDao.TABLENAME"

there error come when in Application start initial dao session and in the activity load all record in table.
