### ISSUE TITLE
A column is always not created on Google Pixel 

### ISSUE THREAD

**Issue by fourplay45** [greenrobot/greenDAO#774]
Reinstall the app for multiple times, but a column never get created in the table.

```
public class MyDaoClass {
    @Unique
    long postId;
    String title;
    String author;
    String source;
    long pubDate;
    String body;
    int likeCount;
    boolean isLike;
    long profileId;  <---------- this column never get created
    ....
}
```

Error Message:

```
Caused by: android.database.sqlite.SQLiteException: no such column: T.PROFILE_ID (code 1): , while compiling: SELECT T."POST_ID",T."PROFILE_ID",T."TITLE",T."AUTHOR",T."SOURCE",T."PUB_DATE",T."BODY",T."LIKE_COUNT",T."IS_LIKE" FROM "POST_DETAIL" T  WHERE T."POST_ID"=?
  at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
  at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
```

Not sure why the problem only happens on Google Pixel (Nougat)

**Comment by greenrobot-team** [comment]
Can you verify that the generated `MyDaoClassDao` contains the `ProfileId` property and the column is actually named `PROFILE_ID`?

There should be a line like: 
```
public final static Property ProfileId = new Property(2, long.class, "profileId", false, "PROFILE_ID");
```

If that is the case, I'm not sure how I can help if I can not reproduce the issue. -ut

**Comment by fourplay45** [comment]
so the code is like:

```
    public static class Properties {
        public final static Property PostId = new Property(0, long.class, "postId", false, "POST_ID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Author = new Property(2, String.class, "author", false, "AUTHOR");
        public final static Property Source = new Property(3, String.class, "source", false, "SOURCE");
        public final static Property PubDate = new Property(4, long.class, "pubDate", false, "PUB_DATE");
        public final static Property Body = new Property(5, String.class, "body", false, "BODY");
        public final static Property LikeCount = new Property(6, int.class, "likeCount", false, "LIKE_COUNT");
        public final static Property IsLike = new Property(7, boolean.class, "isLike", false, "IS_LIKE");
        public final static Property ProfileId = new Property(8, long.class, "profileId", false, "PROFILE_ID");
    }
```

and the error message:
```
E/SQLiteLog: (1) no such column: T.PROFILE_ID
E/ErrorHandlingUtil: network/other error
W/System.err: android.database.sqlite.SQLiteException: no such column: T.PROFILE_ID (code 1): , while compiling: SELECT T."POST_ID",T."TITLE",T."AUTHOR",T."SOURCE",T."PUB_DATE",T."BODY",T."LIKE_COUNT",T."IS_LIKE",T."PROFILE_ID" FROM "POST_DETAIL" T  WHERE T."POST_ID"=?
```

**Comment by greenrobot-team** [comment]
Alright, could you check the `createTable(Database db, boolean ifNotExists)` method in your `MyDaoClassDao` if it actually creates that column?
-ut

**Comment by fourplay45** [comment]
Here is what it looks like now: 
Post.java
![image](https://user-images.githubusercontent.com/20864773/32744243-b832b1e4-c863-11e7-8b62-1aefebc502cb.png)


ProfileDao.java
![image](https://user-images.githubusercontent.com/20864773/32744264-ca254b14-c863-11e7-9db3-20d56d6c3ca4.png)


Please copy & paste the code, run on Google Pixel with latest Nougat or Oreo and see if you can repro and find the issue. Thanks!

**Comment by greenrobot-team** [comment]
Sorry, I do not have access to a Google Pixel device. I tried to reproduce this in an example project and Android Oreo emulator, where it works just fine.

Can you show me how you are querying your `Post` entities? Are you sure this works on other devices (or an Android emulator)?
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by MartinLi2015** [comment]
I met the same problem
