### ISSUE TITLE
Can't create dao generator with gradle 3.0.0 while running green dao generator

### ISSUE THREAD

**Issue by AkhilDad** [greenrobot/greenDAO#795]
Exception in thread "main" java.lang.NoClassDefFoundError: freemarker/template/TemplateNotFoundException
at this line in code (`DaoGenerator daoGenerator = new DaoGenerator();`)
Caused by: java.lang.ClassNotFoundException: freemarker.template.TemplateNotFoundException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

I am using
`implementation 'org.greenrobot:greendao:3.2.0'` in my build.gradle

I had tried 3.2.2 as well.
Same project is working when the gradle version is 2.3.3
<img width="796" alt="screen shot 2017-11-29 at 8 48 47 pm" src="https://user-images.githubusercontent.com/3176478/33382613-3255a57c-d547-11e7-9aa3-8b4af5bef3f3.png">

**Comment by imzhq** [comment]
use gradle run application
![image](https://user-images.githubusercontent.com/16359427/33411297-c31cf2b8-d5bf-11e7-8181-5a213511322d.png)

**Comment by AkhilDad** [comment]
It worked with run, after changing 
`config.setDirectoryForTemplateLoading(new File("../DaoGenerator/src-template/"));`
at line 73 in DaoGenerator.java  
and changing to double dot
` daoGenerator.generateAll(schema, "../app/src/main/java");`

I am using Mac OS
