### ISSUE TITLE
xxxx db has not been initialized

### ISSUE THREAD

**Issue by romichandra** [greenrobot/greenDAO#802]
this crash comes on few samsung, micromax and spice device models, and only on android 5.0,
I have initialized the db in my application class, properly added the proguard rules etc. What could be the issue? Here's the stacktrace: 

Fatal Exception: java.lang.RuntimeException: Unable to create application com.xxxx.xxxx.xxxxApp: java.lang.NullPointerException: xxxx db has not been initialized
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4861)
       at android.app.ActivityThread.access$1500(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1531)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by java.lang.NullPointerException: xxxx db has not been initialized
       at com.xxxx.xxxx.xxxx.xxxxDaoDatabase.getDaoSession(SourceFile:89)
       at com.xxxx.xxxx.xxxxApp.getDaoSession(SourceFile:144)
       at com.xxxx.xxxx.xxxx.repository.PreferencesRepository.getPreferencesDao(SourceFile:61)
       at com.xxxx.xxxx.xxxx.repository.PreferencesRepository.getPreferencesForId(SourceFile:53)
       at com.xxxx.xxxx.xxxx.SeedDatabase.seedPreferences(SourceFile:64)
       at com.xxxx.xxxx.xxxxApp.onCreate(SourceFile:114)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4858)
       at android.app.ActivityThread.access$1500(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1531)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by greenrobot-team** [comment]
Check your code at `com.xxxx.xxxx.xxxx.xxxxDaoDatabase.getDaoSession(SourceFile:89)` and look what method is called there that might return the `NullPointerException`. I suspect there is code that fails to create the database and returns `null`. You should then handle that case if you do not want to crash the app. Typically trying again works.
 -ut

**Comment by romichandra** [comment]
Yes, I do throw a NPE, if the DaoSession object is null. Can I know by some sort of logging or some way to see why it's not been initialized. Since the method calls are synchronous, I might try initializing the db again, but I can handle the cases better if somehow i could know why it failed.

**Comment by greenrobot-team** [comment]
This is Android API. It will likely return some `SQLiteException`. -ut
