### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by RayCourant** [greenrobot/greenDAO#809]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at org.greenrobot.greendao.AbstractDao.executeInsertInTx(AbstractDao.java:281)
	at org.greenrobot.greendao.AbstractDao.insertOrReplaceInTx(AbstractDao.java:250)
	at org.greenrobot.greendao.AbstractDao.insertOrReplaceInTx(AbstractDao.java:259)
	at com.royole.rydrawing.activity.DrawingActivity.p(DrawingActivity.java:1013)
	at com.royole.rydrawing.activity.DrawingActivity.C(DrawingActivity.java:87)
	at com.royole.rydrawing.activity.DrawingActivity$7.a(DrawingActivity.java:728)
	at a.a.g.e.d.z.subscribeActual(ObservableCreate.java:40)
	at a.a.y.subscribe(Observable.java:10910)
	at a.a.g.e.d.de$b.run(ObservableSubscribeOn.java:96)
	at a.a.af$a.run(Scheduler.java:452)
	at a.a.g.g.n.run(ScheduledRunnable.java:61)
	at a.a.g.g.n.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:833)

when I use the insertOrReplaceInTx and then clear DaoSession, in some case it will crash.

mDrawingPathDao.insertOrReplaceInTx(paths);
 mDaoSession.clear();

**Comment by RayCourant** [comment]
I guess that I modify my List in other place when  I use insertOrReplaceInTx.
It result in ConcurrentModificationException.
