### ISSUE TITLE
Make sure the Cursor is initialized correctly before accessing data from it.

### ISSUE THREAD

**Issue by hero0812** [greenrobot/greenDAO#832]
```
java.lang.IllegalStateException: Couldn't read row 1104, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:511)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at org.greenrobot.greendao.AbstractDao.loadCurrent(AbstractDao.java:541)
	at org.greenrobot.greendao.AbstractDao.loadAllUnlockOnWindowBounds(AbstractDao.java:498)
	at org.greenrobot.greendao.AbstractDao.loadAllFromCursor(AbstractDao.java:480)
	at org.greenrobot.greendao.AbstractDao.loadAllAndCloseCursor(AbstractDao.java:203)
	at org.greenrobot.greendao.InternalQueryDaoAccess.loadAllAndCloseCursor(InternalQueryDaoAccess.java:37)
	at org.greenrobot.greendao.query.Query.list(Query.java:89)
	at org.greenrobot.greendao.query.QueryBuilder.list(QueryBuilder.java:427)
	at com.binbin.university.provider.DbManager.queryNewestMsgTime(DbManager.java:263)
	at com.binbin.university.MsgService.getLatetsMsgId(MsgService.java:458)
	at com.binbin.university.MsgService.pullMessageMethod(MsgService.java:260)
	at com.binbin.university.MsgService.access$200(MsgService.java:64)
	at com.binbin.university.MsgService$4$1.run(MsgService.java:420)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by AangJnr** [comment]
I don't know if this is going to help anyone or if its related whatsoever but make sure the table column names do not start with a space character eg. " last_modified_date".

**Comment by greenrobot-team** [comment]
@hero0812 Without an example project to reproduce this, there is not much we can do.

Please re-open if you have more information (like an example project that has this issue). -ut

**Comment by zhouxin1233** [comment]
java.lang.IllegalStateException: Couldn't read row 2587, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetLong(Native Method)
at android.database.CursorWindow.getLong(CursorWindow.java:511)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
at org.greenrobot.greendao.AbstractDao.loadCurrent(Proguard:541)
bindValues
bindValues
updateKeyAfterInsert
at org.greenrobot.greendao.AbstractDao.loadAllUnlockOnWindowBounds(Proguard:498)
bindValues
bindValues
updateKeyAfterInsert
at org.greenrobot.greendao.AbstractDao.loadAllFromCursor(Proguard:480)
at org.greenrobot.greendao.AbstractDao.loadAllAndCloseCursor(Proguard:203)
at org.greenrobot.greendao.InternalQueryDaoAccess.loadAllAndCloseCursor(Proguard:37)
at org.greenrobot.greendao.query.Query.list(Proguard:89)
at org.greenrobot.greendao.query.QueryBuilder.list(Proguard:427)
at com.baidu.input.db.greendao.table.ImgBeanManger.getNotUseChatFromDb(Proguard:283)

**Comment by pahmedadel** [comment]
may be space when declare variable 
public static final String  USERS_ID_CLN = " USER_ID";
must be no space 
public static final String  USERS_ID_CLN = "USER_ID";
