### ISSUE TITLE
NoClassDefFoundError when trying to run DaoGenerator for GreenDAO

### ISSUE THREAD

**Issue by Rakesh437** [greenrobot/greenDAO#836]
I have an Android Project, developed using Android Studio 2.3.1, which uses GreenDAO to generate the classes to add or update tables. The DaoGenerator always used to work before i updated Android Studio to 3.0.1. After the update DaoGenerator gives following error:-

Exception in thread "main" java.lang.NoClassDefFoundError: org/greenrobot/greendao/generator/Schema at com.greendao.GreenDaoDBGenerator.main(GreenDaoDBGenerator.java:18)
Caused by: java.lang.ClassNotFoundException: org.greenrobot.greendao.generator.Schema
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

This is generator gradle:-

apply plugin: 'java'
apply plugin: 'application'
mainClassName = "com.greendao.GreenDaoDBGenerator"
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
   compile 'org.greenrobot:greendao-generator:3.2.2'
}

              I have added classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2' in project gradle and  compile 'org.greenrobot:greendao:3.2.2' in app-gradle.

            I already tried using 'run' task of generator gradle but its not working. Did anybody else faced the same issue? Can anyone help me out to solve it.

             Thanks in advance.

**Comment by andrewindayang** [comment]
yes, i got that problem without any code changes. can any one solve this please i have read all the comments by adding 

apply plugin: 'application'
mainClassName = "com.pmrpallet.ProductionAppDao"

but i still cant solve this issue. 

Exception in thread "main" java.lang.NoClassDefFoundError: org/greenrobot/greendao/generator/Schema
	at com.daogenerator.DaoGenerator.main(DaoGenerator.java:40)
Caused by: java.lang.ClassNotFoundException: org.greenrobot.greendao.generator.Schema
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

"http://greenrobot.org/greendao/documentation/generator/#Triggering_generation"

the run from gradle all went well but when i run this application still had Schema issue.
![screen shot 2018-03-18 at 11 37 46 pm](https://user-images.githubusercontent.com/5306027/37568271-6a106c72-2b05-11e8-975a-8eed529b59e5.png)

**Comment by andrewindayang** [comment]
Hi @Rakesh437 

i just solved mine


        Schema schema = new Schema(DB_VERSION, "com.GreendaoGen.GenerateDAO");
        schema.enableKeepSectionsByDefault();
        addEntitiesToSchema(schema);

        try {
            new org.greenrobot.greendao.generator.DaoGenerator().generateAll(schema, "../app/src/main/java");
        } catch (Exception e) {
            e.printStackTrace();
        }


check ur generate ALL path. it needs 2 dots on front. and then on your android studio top right had 
![screen shot 2018-03-19 at 12 42 55 am](https://user-images.githubusercontent.com/5306027/37568929-7a218674-2b0e-11e8-9d0e-8254e50f29e4.png)

expand that section and you will see the application > run double click on that. And now on your run u will have 1 gradle for dao and 1 gradle for your app. dont use application anymore.
 
![screen shot 2018-03-19 at 12 43 07 am](https://user-images.githubusercontent.com/5306027/37568932-88a85a06-2b0e-11e8-8eeb-58f201eefcee.png)

**Comment by greenrobot-team** [comment]
@andrewindayang Thanks for helping out. Closing because no response. -ut
