### ISSUE TITLE
Error:Execution failed for task ':app:kaptDebugKotlin'.

### ISSUE THREAD

**Issue by ZhouBey** [greenrobot/greenDAO#838]
/Users/zpy/AndroidStudioProjects/mxz-app-android/app/src/main/java/cc/komiko/mengxiaozhuapp/App.java:78: 错误: 找不到符号
e: 

e:     private SystemMessageDao messageDao;
e:             ^
e:   符号:   类 SystemMessageDao
e:   位置: 类 App
e: /Users/zpy/AndroidStudioProjects/mxz-app-android/app/src/main/java/cc/komiko/mengxiaozhuapp/App.java:80: 错误: 找不到符号
e: 

e:     private SystemMessagePushDao messagePushDao;
e:             ^
e:   符号:   类 SystemMessagePushDao
e:   位置: 类 App
e: /Users/zpy/AndroidStudioProjects/mxz-app-android/app/src/main/java/cc/komiko/mengxiaozhuapp/App.java:82: 错误: 找不到符号
e: 

e:     private PlanDao planDao;
e:             ^
e:   符号:   类 PlanDao
e:   位置: 类 App
e: /Users/zpy/AndroidStudioProjects/mxz-app-android/app/src/main/java/cc/komiko/mengxiaozhuapp/App.java:84: 错误: 找不到符号
e: 

e:     private NewPlanDao newPlanDao;
e:             ^
e:   符号:   类 NewPlanDao
e:   位置: 类 App
e: /Users/zpy/AndroidStudioProjects/mxz-app-android/app/src/main/java/cc/komiko/mengxiaozhuapp/App.java:393: 错误: 找不到符号
e: 

e:     public SystemMessageDao getMessageDao() {
e:            ^
e:   符号:   类 SystemMessageDao
e:   位置: 类 App
e: /Users/zpy/AndroidStudioProjects/mxz-app-android/app/src/main/java/cc/komiko/mengxiaozhuapp/App.java:402: 错误: 找不到符号
e: 

e:     public PlanDao getPlanDao() {
e:            ^
e:   符号:   类 PlanDao
e:   位置: 类 App
e: /Users/zpy/AndroidStudioProjects/mxz-app-android/app/src/main/java/cc/komiko/mengxiaozhuapp/App.java:418: 错误: 找不到符号
e: 

e:     public NewPlanDao getNewPlanDao() {
e:            ^
e:   符号:   类 NewPlanDao
e:   位置: 类 App
e: /Users/zpy/AndroidStudioProjects/mxz-app-android/app/src/main/java/cc/komiko/mengxiaozhuapp/App.java:426: 错误: 找不到符号
e: 

e:     public SystemMessagePushDao getMessagePushDao() {
e:            ^
e:   符号:   类 SystemMessagePushDao
e:   位置: 类 App
e: /Users/zpy/AndroidStudioProjects/mxz-app-android/app/src/main/java/cc/komiko/mengxiaozhuapp/fragment/AppFragment.java:61: 错误: 仅从类和接口静态导入
e: 

e: import static cc.komiko.mengxiaozhuapp.model.NewPlanDao.Properties.Mid;
e: ^
e: /Users/zpy/AndroidStudioProjects/mxz-app-android/app/src/main/java/cc/komiko/mengxiaozhuapp/util/GreenDaoOpenHelper.java:14: 错误: 仅从类和接口静态导入
e: 

e: import static cc.komiko.mengxiaozhuapp.model.DaoMaster.SCHEMA_VERSION;
e: ^
e: /Users/zpy/AndroidStudioProjects/mxz-app-android/app/src/main/java/cc/komiko/mengxiaozhuapp/util/GreenDaoOpenHelper.java:15: 错误: 仅从类和接口静态导入
e: 

e: import static cc.komiko.mengxiaozhuapp.model.DaoMaster.createAllTables;
e: ^
e: java.lang.IllegalStateException: failed to analyze: org.jetbrains.kotlin.kapt3.diagnostic.KaptError: Error while annotation processing
	at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:57)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:138)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:154)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:58)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:103)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$2.invoke(CompileServiceImpl.kt:386)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$2.invoke(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:889)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:916)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:888)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:385)
	at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jetbrains.kotlin.kapt3.diagnostic.KaptError: Error while annotation processing
	at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:90)
	at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:42)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:205)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:166)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:82)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:106)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:83)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:377)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:68)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:368)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:133)
	... 29 more

**Comment by greenrobot-team** [comment]
See if [my comment on Kotlin support helps](https://github.com/greenrobot/greenDAO/issues/395#issuecomment-304582750). -ut

**Comment by MFori** [comment]
Not working with 'kotlin-kapt' plugin

**Comment by Fubiven** [comment]
config daoPackage

**Comment by kerolsafififawzy** [comment]
a7a
