### ISSUE TITLE
org.greenrobot.greendao.DaoException: Could not init DAOConfig

### ISSUE THREAD

**Issue by himangipatel** [greenrobot/greenDAO#877]
I am using proguard in my application and I have to put obfuscation in my app source code.
I am not able to lanuch my application if I added proguad and its only cause b'coz of greendao initialization. If I remove greendao initialization then it works perfact

**I have use below greendao proguard rules:** 

-keep class de.greenrobot.**
-keep class  org.greenrobot.**
-keep class * extends de.greenrobot.**

-keepclassmembers class * extends de.greenrobot.dao.AbstractDao {
    public static java.lang.String TABLENAME;
}
-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }

-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}

 org.greenrobot.greendao.DaoException: Could not init DAOConfig
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: org.greenrobot.greendao.DaoException: Could not init DAOConfig
        at org.greenrobot.greendao.internal.DaoConfig.<init>(Unknown Source:205)
        at org.greenrobot.greendao.AbstractDaoMaster.a(Unknown Source:4)

**Comment by noman-augmedix** [comment]
Keep the package which you put your Entity class.
`-keep class com.xxx.xxx.model.* {*;}`
