### ISSUE TITLE
net.sqlcipher.database.SQLiteException

### ISSUE THREAD

**Issue by zl422341743** [greenrobot/greenDAO#889]
When using  Sqlcipher  to encrypt encryption, this error occurs when data is updated, and all data is emptied when it occurs.

 Caused by: net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database
        at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
        at net.sqlcipher.database.SQLiteStatement.execute(SQLiteStatement.java:58)
        at org.greenrobot.greendao.database.EncryptedDatabaseStatement.execute(EncryptedDatabaseStatement.java:31)
        at org.greenrobot.greendao.AbstractDao.updateInsideSynchronized(AbstractDao.java:808)
        at org.greenrobot.greendao.AbstractDao.update(AbstractDao.java:783)

**Comment by greenrobot-team** [comment]
`error code 8: attempt to write a readonly database`

Are you maybe passing a read-only database to `DaoMaster´?
-ut

**Comment by greenrobot-team** [comment]
Closing this issue due to inactivity. :zzz: Please re-open with more details or submit a new issue.
