### ISSUE TITLE
resource leaks

### ISSUE THREAD

**Issue by ZhenMrLee** [greenrobot/greenDAO#894]
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:184)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:837)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:821)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1286)
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
        at org.greenrobot.greendao.database.DatabaseOpenHelper.getWritableDb(DatabaseOpenHelper.java:59)
 at com.packet.Application.getDBSession(Application.java:56)

lead to 
  daoMaster = new DaoMaster(devOpenHelper.getWritableDb());

**Comment by greenrobot-team** [comment]
greenDAO assumes that you keep the `DaoMaster` instance throughout the life-time of your app (for example in a singleton).

If that is not the case, make sure to call `close()` on the database helper after you are done with `DaoMaster`. Then you can create a new `DaoMaster` at a later point.

Closing. Please re-open if your question was not answered.
-ut
