### ISSUE TITLE
android.database.sqlite.SQLiteException: Failed to change locale for db '/*/password.db' to 'zh_CN'

### ISSUE THREAD

**Issue by Hommilist** [greenrobot/greenDAO#901]
at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:397)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:829)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:814)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:709)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1029)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1018)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:250)
	at com.android.org.chromium.android_webview.PasswordDatabase.initDatabase(PasswordDatabase.java:118)
	at com.android.org.chromium.android_webview.PasswordDatabase.initOnBackgroundThread(PasswordDatabase.java:99)
	at com.android.org.chromium.android_webview.PasswordDatabase.access$000(PasswordDatabase.java:10)
	at com.android.org.chromium.android_webview.PasswordDatabase$1.run(PasswordDatabase.java:83)
Caused by: android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:559)
	at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:371)
	... 15 more
android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:559)
	at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:371)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:829)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:814)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:709)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1029)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1018)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:250)
	at com.android.org.chromium.android_webview.PasswordDatabase.initDatabase(PasswordDatabase.java:118)
	at com.android.org.chromium.android_webview.PasswordDatabase.initOnBackgroundThread(PasswordDatabase.java:99)
	at com.android.org.chromium.android_webview.PasswordDatabase.access$000(PasswordDatabase.java:10)
	at com.android.org.chromium.android_webview.PasswordDatabase$1.run(PasswordDatabase.java:83)

**Comment by bigbigpeng3** [comment]
@Hommilist Did you solved this problem ？How？

**Comment by greenrobot-team** [comment]
Looking at the stack trace: `SQLiteFullException: database or disk is full (code 13)`

Closing.
-ut

**Comment by didixyy** [comment]
i also have this problem   like this
 https://stackoverflow.com/questions/21155598/android-sqlite-failed-to-change-locale-for-db-to-zh-cn/21155951  how can i fix it
