### ISSUE TITLE
Crashes in SAMSUNG GALAXY S3 4.1.2

### ISSUE THREAD

**Issue by pintuag** [greenrobot/greenDAO#909]
Fatal Exception: java.lang.NoClassDefFoundError: org.greenrobot.greendao.database.StandardDatabase
       at org.greenrobot.greendao.database.DatabaseOpenHelper.wrap(DatabaseOpenHelper.java:71)
       at org.greenrobot.greendao.database.DatabaseOpenHelper.onCreate(DatabaseOpenHelper.java:79)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
       at org.greenrobot.greendao.database.DatabaseOpenHelper.getWritableDb(DatabaseOpenHelper.java:59)
       at com.zomeds.zomedswarehouse.AppController.onCreate(AppController.java:23)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4264)
       at android.app.ActivityThread.access$1400(ActivityThread.java:140)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4946)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1036)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:803)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by greenrobot-team** [comment]
This is an issue with your code, not greenDAO. Search for `NoClassDefFoundError`. This likely is due to ProGuard removing a required class from your final APK.
-ut
