### ISSUE TITLE
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)

### ISSUE THREAD

**Issue by wqxcloud** [greenrobot/greenDAO#925]
When i use greendao, i get this error,Can you help me? Thanks
```
11-15 16:35:09.946 D/AndroidRuntime(14860): Shutting down VM
11-15 16:35:09.948 E/AndroidRuntime(14860): FATAL EXCEPTION: main
11-15 16:35:09.948 E/AndroidRuntime(14860): Process: com.xxx, PID: 14860
11-15 16:35:09.948 E/AndroidRuntime(14860): java.lang.RuntimeException: Unable to resume activity {com.xxx/xxxx.mvp.view.activity.LeadingMainActivity}: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2986)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.os.Looper.loop(Looper.java:135)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at java.lang.reflect.Method.invoke(Native Method)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at java.lang.reflect.Method.invoke(Method.java:372)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
11-15 16:35:09.948 E/AndroidRuntime(14860): Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:634)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:320)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1148)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at org.greenrobot.greendao.database.DatabaseOpenHelper.getWritableDb(DatabaseOpenHelper.java:59)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at com.xxx.impl.DclContactServiceImpl.initDao(DclContactServiceImpl.java:75)
11-15 16:35:09.948 E/AndroidRuntime(14860): 	at com.xxx.impl.DclContactServiceImpl.<init>(DclContactServiceImpl.java:69)
```

**Comment by greenrobot-team** [comment]
Your code probably tries to initialize your DatabaseOpenHelper again even you already did so.

Either make sure to only initialize it once or close the old one (and the database) before opening it again.

-ut
