### ISSUE TITLE
Can't insert into database

### ISSUE THREAD

**Issue by bxjxxyy** [greenrobot/greenDAO#927]
Code In MyApplication : 
```
   private void setupDatabase(){
        DaoMaster.DevOpenHelper helper=new DaoMaster.DevOpenHelper(this,"zrb.db",null);
        SQLiteDatabase db=helper.getWritableDatabase();
        DaoMaster daoMaster=new DaoMaster(db);
        daoSession = daoMaster.newSession();
    }
    public static DaoSession getDaoInstant(){
        return daoSession;
    }
```
Code when I want to insert into database:
`    MyApplication.getDaoInstant().getUserBeanDao().insert(model);`
This line will crash,and error msg is below :
```
  android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1548)
        at android.database.sqlite.SQLiteDatabase.replace(SQLiteDatabase.java:1464)
        at com.mob.commons.logcollector.b.a(DBProvider.java:57)
```

But if when I need to do insert, new  DaoMaster.DevOpenHelper ,new  SQLiteDatabase ,new DaoMaster ,new daoSession   every time ,then I can insert.  But this way may case `android.database.sqlite.SQLiteDiskIOException:  disk  I/O  error  (code  522  SQLITE_IOERR_SHORT_READ): `

**Comment by greenrobot-team** [comment]
The stack trace you provided does not seem related to greenDAO code. Even if, an insert definitely will not call `SQLiteDatabase.replace`.

Check your code at com.mob.commons.logcollector.b.a(DBProvider.java:57) and see if it gets a writable database.

-ut
