### ISSUE TITLE
Make sure the Cursor is initialized correctly before accessing data from it

### ISSUE THREAD

**Issue by zhouxin1233** [greenrobot/greenDAO#941]
java.lang.IllegalStateException: Couldn't read row 2587, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetLong(Native Method)
at android.database.CursorWindow.getLong(CursorWindow.java:511)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
at org.greenrobot.greendao.AbstractDao.loadCurrent(Proguard:541)
bindValues
bindValues
updateKeyAfterInsert
at org.greenrobot.greendao.AbstractDao.loadAllUnlockOnWindowBounds(Proguard:498)
bindValues
bindValues
updateKeyAfterInsert
at org.greenrobot.greendao.AbstractDao.loadAllFromCursor(Proguard:480)
at org.greenrobot.greendao.AbstractDao.loadAllAndCloseCursor(Proguard:203)
at org.greenrobot.greendao.InternalQueryDaoAccess.loadAllAndCloseCursor(Proguard:37)
at org.greenrobot.greendao.query.Query.list(Proguard:89)
at org.greenrobot.greendao.query.QueryBuilder.list(Proguard:427)
at com.baidu.input.db.greendao.table.ImgBeanManger.getNotUseChatFromDb(Proguard:283)

**Comment by greenrobot-team** [comment]
@zhouxin1233 Please share an example project so we can reproduce this. Otherwise we can not fix this issue.
-ut

**Comment by greenrobot-team** [comment]
Closing this issue due to inactivity. :zzz: Please re-open with more details or submit a new issue.

**Comment by Tan-Tshunglee** [comment]
Keep the classes generated by greedao from proguard may solve this issue
