### ISSUE TITLE
Can't find property for index

### ISSUE THREAD

**Issue by populater** [greenrobot/greenDAO#957]
GreenDAO fails building app when adding an index to an Entity:

	static void addTables(final Schema schema) {
		Entity game = addGameEntity(schema);
		Entity shop = addShopEntity(schema);
		Entity tag = addTagEntity(schema);

		//Indexes
		Index tagIndex = new Index();

		//PKs
		Property gameId = game.addLongProperty("gameId").dbName("game_id").primaryKey().autoincrement().getProperty();
		Property shopId = shop.addLongProperty("shopId").dbName("shop_id").primaryKey().autoincrement().getProperty();

		//Relationships 1-1
		tag.addToOne(game, gameId, "game");
		tag.addToOne(shop, shopId, "shop");

		//Composite keys (created as unique indexes)
		tagIndex.addProperty(gameId);
		tagIndex.addProperty(shopId);
		tag.addIndex(tagIndex);
	}

	private static Entity addGameEntity(final Schema schema) {
		Entity entity = schema.addEntity("Game");
		entity.addStringProperty("gameName").dbName("game_name").notNull();
		return entity;
	}

	private static Entity addShopEntity(final Schema schema) {
		Entity entity = schema.addEntity("Shop");
		entity.addStringProperty("shopName").dbName("shop_name").notNull();
		return entity;
	}

	private static Entity addTagEntity(final Schema schema) {
		Entity entity = schema.addEntity("Tag");
		entity.addDoubleProperty("tagPrice").dbName("tag_price").notNull();
		return entity;
	}

When building Android app, this happens:

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:greendao'.
> Can't find property gameId for index in Tag

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:greendao'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: Can't find property gameId for index in Tag
	at org.greenrobot.greendao.codemodifier.GreendaoModelTranslator.addIndexes(GreendaoModelTranslator.kt:84)
	at org.greenrobot.greendao.codemodifier.GreendaoModelTranslator.mapEntityClassesToEntities(GreendaoModelTranslator.kt:39)
	at org.greenrobot.greendao.codemodifier.GreendaoModelTranslator.translate(GreendaoModelTranslator.kt:21)
	at org.greenrobot.greendao.codemodifier.Greendao3Generator.generateSchema(Greendao3Generator.kt:70)
	at org.greenrobot.greendao.codemodifier.Greendao3Generator.run(Greendao3Generator.kt:57)
	at org.greenrobot.greendao.gradle.Greendao3GradlePlugin$createGreendaoTask$$inlined$apply$lambda$1.execute(Greendao3GradlePlugin.kt:90)
	at org.greenrobot.greendao.gradle.Greendao3GradlePlugin$createGreendaoTask$$inlined$apply$lambda$1.execute(Greendao3GradlePlugin.kt:14)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 27 more`

**Comment by greenrobot-team** [comment]
Simple: as the message says (`Can't find property gameId for index in Tag`) your `Tag` entity does not have a property called `gameId`. So obviously you can not create an index on it.

Suggestion: move to greenDAO 3 and entity annotations. This makes it a lot more clear what is actually possibly, including indexes.
http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/
http://greenrobot.org/greendao/documentation/modelling-entities/#Property_indexes

-Uwe
-- [Check out ObjectBox](https://objectbox.io), our new fast, easy to use database!
