### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by androiddk1** [greenrobot/greenDAO#992]
Caused by: android.database.sqlite.SQLiteException: table MODEL_INFO_ENTITY has no column named _id (Sqlite code 1 SQLITE_ERROR): , while compiling: INSERT INTO "MODEL_INFO_ENTITY" ("_id","MACHINE_ID","NAME","TYPE","IS_SELECT","IMG_URL","COUNT","DATE","CHILDREN_LIST") VALUES (?,?,?,?,?,?,?,?,?), (OS error - 2:No such file or directory)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:948)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:559)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:603)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1166)
        at org.greenrobot.greendao.database.StandardDatabase.compileStatement(StandardDatabase.java:67)
        at org.greenrobot.greendao.internal.TableStatements.getInsertStatement(TableStatements.java:52)
        at org.greenrobot.greendao.AbstractDao.insertInTx(AbstractDao.java:236)
        at org.greenrobot.greendao.AbstractDao.insertInTx(AbstractDao.java:215)

![image](https://user-images.githubusercontent.com/5069404/64746451-2790cb00-d53e-11e9-809a-9d6be44e4bca.png)

**Comment by greenrobot-team** [comment]
The stack trace includes `OS error - 2:No such file or directory`. Was the database file maybe deleted in the meantime?

Also, if you are using SQLcipher https://github.com/greenrobot/greenDAO/issues/634 may have a solution.
