### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object org.greenrobot.greendao.database.Database.getRawDatabase()' on a null object reference

### ISSUE THREAD

**Issue by chenyunecjtu** [greenrobot/greenDAO#995]

**Comment by chenyunecjtu** [comment]
adb log 
`

09-16 15:42:02.016 21870 21870 V ActivityThread: callActivityOnCreate
--
209-16 15:42:02.020 21870 21870 I HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=0, mNavBarShow=false, mIsFloating=false
309-16 15:42:02.020 21870 21870 I HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=true, mForcedNavigationBarColor=false, navigationBarColor=fffcfcfc, mNavBarShow=false, mIsFloating=false
409-16 15:42:02.029 21870 21870 I HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=true, mForcedNavigationBarColor=false, navigationBarColor=fffcfcfc, mNavBarShow=false, mIsFloating=false
509-16 15:42:02.030 21870 21870 D ActivityThread: add activity client record, r= ActivityRecord{b00e83e token=android.os.BinderProxy@3e8069a {com.yuwan.zbshipin/com.yuwan.meet.activity.LoginActivity}} token= android.os.BinderProxy@3e8069a
609-16 15:42:02.031 21870 21870 D ZrHung.AppEyeUiProbe: notify runnable to start.
709-16 15:42:02.031 21870 21870 V MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.yuwan.meet.activity.LoginActivity onActivityResumed
809-16 15:42:02.033 21870 21932 D OpenGLRenderer: HWUI Binary is enabled
909-16 15:42:02.033 21870 21932 D OpenGLRenderer: disableOutlineDraw is true
1009-16 15:42:02.043 21870 21870 I HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=true, mForcedNavigationBarColor=false, navigationBarColor=fffcfcfc, mNavBarShow=true, mIsFloating=false
1109-16 15:42:02.045 21870 22121 I HiTouch_HiTouchSensor: enabledInPad = false,isPcCastMode = false
1209-16 15:42:02.046 21870 22121 D HiTouch_PressGestureDetector: onAttached, package=com.yuwan.zbshipin, windowType=1, mHiTouchRestricted=false
1309-16 15:42:02.052 21870 21932 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
1409-16 15:42:02.053 21870 21870 I ansen : onGlobalLayout:
1509-16 15:42:02.086 21870 21870 I ansen : toXValue:1045.0
1609-16 15:42:02.092 21870 21932 D OpenGLRenderer: HWUI Binary is enabled
1709-16 15:42:02.092 21870 21932 D OpenGLRenderer: disableOutlineDraw is true
1809-16 15:42:02.113 21870 21870 W InputMethodManager: startInputReason = 1
1909-16 15:42:02.419 21870 21932 W libEGL : EGLNativeWindowType 0xc733c008 disconnect failed
2009-16 15:42:02.425 21870 21932 W libEGL : EGLNativeWindowType 0xbe54b808 disconnect failed
2109-16 15:42:02.434 21870 21932 W libEGL : EGLNativeWindowType 0xca141808 disconnect failed
2209-16 15:42:02.443 21870 21932 W libEGL : EGLNativeWindowType 0xdaf7c808 disconnect failed
2309-16 15:42:02.836 21870 21870 V MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: WXStat trigger onForeground
2409-16 15:42:02.904 21870 22099 E MtaSDK : [pool-11-thread-1(1680): null:841] - Server response error code:404, error:{"ret":-1, "msg":"invalid appkey"}
2509-16 15:42:03.902 21870 21870 V MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.yuwan.meet.activity.LoginActivity onActivityPaused
2609-16 15:42:03.903 21870 21870 D ZrHung.AppEyeUiProbe: stop checker.
2709-16 15:42:04.059 21870 21870 D ViewRootImpl[LoginActivity]: surface should not be released
2809-16 15:42:04.061 21870 21870 D ActivityThread: Remove activity client record, r= ActivityRecord{6838b8d token=android.os.BinderProxy@e9a1d63 {com.yuwan.zbshipin/com.yuwan.meet.activity.LoginActivity}} token= android.os.BinderProxy@e9a1d63
2909-16 15:42:04.072 21870 21870 D ViewRootImpl[LoginActivity]: surface should not be released
3009-16 15:42:04.075 21870 21870 D ActivityThread: Remove activity client record, r= ActivityRecord{c00b9f5 token=android.os.BinderProxy@1c79cf6 {com.yuwan.zbshipin/com.yuwan.meet.activity.LoginActivity}} token= android.os.BinderProxy@1c79cf6
3109-16 15:42:04.081 21870 21870 D ViewRootImpl[MainActivity]: surface should not be released
3209-16 15:42:04.090 21870 21870 D ActivityThread: Remove activity client record, r= ActivityRecord{f5ea850 token=android.os.BinderProxy@3707fd8 {com.yuwan.zbshipin/com.yuwan.meet.activity.MainActivity}} token= android.os.BinderProxy@3707fd8
3309-16 15:42:04.139 21870 21870 D ViewRootImpl[LauncherActivity]: surface should not be released
3409-16 15:42:04.140 21870 21870 D ActivityThread: Remove activity client record, r= ActivityRecord{443123e token=android.os.BinderProxy@b8a5d51 {com.yuwan.zbshipin/com.yuwan.meet.activity.LauncherActivity}} token= android.os.BinderProxy@b8a5d51
3509-16 15:42:04.230 21870 21929 D ZrHung.AppEyeUiProbe: Current Activity:false
3609-16 15:42:04.230 21870 21929 D ZrHung.AppEyeUiProbe: not watching, wait.
3709-16 15:42:04.487 21870 21932 W libEGL : EGLNativeWindowType 0xc9e43008 disconnect failed
3809-16 15:42:04.502 21870 21870 D ViewRootImpl[LoginActivity]: surface should not be released
3909-16 15:42:04.505 21870 21870 D ActivityThread: Remove activity client record, r= ActivityRecord{b00e83e token=android.os.BinderProxy@3e8069a {com.yuwan.zbshipin/com.yuwan.meet.activity.LoginActivity}} token= android.os.BinderProxy@3e8069a
4009-16 15:42:04.625 21870 21870 D AwareBitmapCacher: handleInit switch not opened pid=21870
4109-16 15:42:04.703 21870 21870 V MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: WXStat trigger onBackground
4209-16 15:42:05.348 21970 22036 D PushService: clientid is a7e40a55f2b80b97e2db1cbf10f49750
4309-16 15:42:05.423 21970 21994 I pin:pushservic: Waiting for a blocking GC ProfileSaver
4409-16 15:42:05.434 21970 21970 D AwareBitmapCacher: handleInit disable com.yuwan.zbshipin:pushservice
4509-16 15:42:05.493 21970 21994 I pin:pushservic: WaitForGcToComplete blocked ProfileSaver on AddRemoveAppImageSpace for 70.248ms
4609-16 15:42:05.499 22003 22003 D AwareBitmapCacher: handleInit disable com.yuwan.zbshipin:remote
4709-16 15:42:05.708 21970 22059 W ServiceManager: Service huawei.android.security.IAppBehaviorDataAnalyzer didn't start. Returning NULL
4809-16 15:42:05.708 21970 22059 E [HOTFIX]: [ThreadDexHotfixMonitor]Bind hotfix monitor service fail!
4909-16 15:42:08.446 21870 21954 I UtilsSDK: Thread Pool is close
5009-16 15:42:10.512 21970 22036 V AudioManager: isMusicActive...
5109-16 15:42:10.896 21970 21970 W Thread-8: type=1400 audit(0.0:41152): avc: granted { create } for name="gktper" scontext=u:r:untrusted_app:s0:c196,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0:c196,c256,c512,c768 tclass=file
5209-16 15:42:10.896 21970 21970 W Thread-8: type=1400 audit(0.0:41153): avc: granted { create } for name="gktper" scontext=u:r:untrusted_app:s0:c196,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0:c196,c256,c512,c768 tclass=file
5309-16 15:42:10.992 21970 21970 W Thread-8: type=1400 audit(0.0:41154): avc: granted { create } for name="gkt-shm" scontext=u:r:untrusted_app:s0:c196,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0:c196,c256,c512,c768 tclass=file
5409-16 15:42:11.654 21870 22103 D skia : external skia timerHandler destroy skip because of hasvisit.
5509-16 15:42:12.749 21870 21870 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@196556c
5609-16 15:42:12.806 21870 21870 D ZrHung.AppEyeUiProbe: notify runnable to start.
5709-16 15:42:12.806 21870 21870 V ActivityThread: Skipping new config:{1.0 460mcc3mnc [zh_CN_#Hans] ldltr sw360dp w360dp h710dp 480dpi nrml long hdr port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 88 - 1080, 2218) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.8}, config:{1.0 460mcc3mnc [zh_CN_#Hans] ldltr sw360dp w360dp h710dp 480dpi nrml long hdr port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 88 - 1080, 2218) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.8} for app:com.yuwan.zbshipin
5809-16 15:42:12.807 21870 21929 D ZrHung.AppEyeUiProbe: restart watching
5909-16 15:42:12.834 21870 21870 V ActivityThread: callActivityOnCreate
6009-16 15:42:12.838 21870 21870 I HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=0, mNavBarShow=false, mIsFloating=false
6109-16 15:42:12.838 21870 21870 I HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=true, mForcedNavigationBarColor=false, navigationBarColor=fffcfcfc, mNavBarShow=false, mIsFloating=false
6209-16 15:42:12.853 21870 21870 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
6309-16 15:42:12.853 21870 21870 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
6409-16 15:42:12.853 21870 21870 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
6509-16 15:42:12.853 21870 21870 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
6609-16 15:42:12.853 21870 21870 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@6788b88,com.yuwan.meet.activity.P2PChatActivity@e495c58
6709-16 15:42:12.853 21870 21870 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
6809-16 15:42:12.853 21870 21870 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
6909-16 15:42:12.854 21870 21870 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
7009-16 15:42:12.854 21870 21870 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
7109-16 15:42:12.854 21870 21870 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
7209-16 15:42:12.854 21870 21870 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@6ced834,com.yuwan.meet.activity.P2PChatActivity@e495c58
7309-16 15:42:12.854 21870 21870 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
7409-16 15:42:12.854 21870 21870 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
7509-16 15:42:12.854 21870 21870 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
7609-16 15:42:12.854 21870 21870 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
7709-16 15:42:12.854 21870 21870 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
7809-16 15:42:12.854 21870 21870 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@5aa0bd2,com.yuwan.meet.activity.P2PChatActivity@e495c58
7909-16 15:42:12.854 21870 21870 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
8009-16 15:42:12.854 21870 21870 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
8109-16 15:42:12.854 21870 21870 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
8209-16 15:42:12.854 21870 21870 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
8309-16 15:42:12.854 21870 21870 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
8409-16 15:42:12.854 21870 21870 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@9b43a0,com.yuwan.meet.activity.P2PChatActivity@e495c58
8509-16 15:42:12.854 21870 21870 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
8609-16 15:42:12.854 21870 21870 I ansen : PullRefreshLayout onFinishInflate
8709-16 15:42:12.854 21870 21870 I ansen : supportAutoLoadMore recyclerView:android.support.v7.widget.RecyclerView{e76bb59 VFED..... ......I. 0,0-0,0 #7f090255 app:id/recyclerview}
8809-16 15:42:12.884 21870 21870 D HwWechatOptimizeImpl: mIsEffect:false
8909-16 15:42:12.908 21870 21870 I ansen : realKeyboardHeight:0
9009-16 15:42:12.915 21870 21870 D AndroidRuntime: Shutting down VM
91--------- beginning of crash
9209-16 15:42:12.927 21870 21870 E AndroidRuntime: FATAL EXCEPTION: main
9309-16 15:42:12.927 21870 21870 E AndroidRuntime: Process: com.yuwan.zbshipin, PID: 21870
9409-16 15:42:12.927 21870 21870 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yuwan.zbshipin/com.yuwan.meet.activity.P2PChatActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object org.greenrobot.greendao.database.Database.getRawDatabase()' on a null object reference
9509-16 15:42:12.927 21870 21870 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
9609-16 15:42:12.927 21870 21870 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
9709-16 15:42:12.927 21870 21870 E AndroidRuntime: at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
9809-16 15:42:12.927 21870 21870 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
9909-16 15:42:12.927 21870 21870 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
10009-16 15:42:12.927 21870 21870 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
10109-16 15:42:12.927 21870 21870 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:112)
10209-16 15:42:12.927 21870 21870 E AndroidRuntime: at android.os.Looper.loop(Looper.java:216)
10309-16 15:42:12.927 21870 21870 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7625)
10409-16 15:42:12.927 21870 21870 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
10509-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
10609-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
10709-16 15:42:12.927 21870 21870 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object org.greenrobot.greendao.database.Database.getRawDatabase()' on a null object reference
10809-16 15:42:12.927 21870 21870 E AndroidRuntime: at org.greenrobot.greendao.AbstractDao.<init>(SourceFile:85)
10909-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.app.model.dao.bean.ChatUserDMDao.<init>(SourceFile:40)
11009-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.app.model.dao.bean.DaoSession.<init>(SourceFile:49)
11109-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.app.model.dao.bean.DaoMaster.newSession(SourceFile:58)
11209-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.app.model.dao.DaoManager.getDaoSession(SourceFile:67)
11309-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.app.model.dao.bean.ChatMsgDM.dao(SourceFile:429)
11409-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.app.greendaoadapter.d.findBy(SourceFile:157)
11509-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.app.greendaoadapter.d.findAll(SourceFile:177)
11609-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.app.model.dao.bean.ChatMsgDM.getGroupMessages(SourceFile:761)
11709-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.app.model.dao.bean.ChatMsgDM.getUserMessages(SourceFile:790)
11809-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.yuwan.meet.e.av.a(SourceFile:121)
11909-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.yuwan.meet.activity.P2PChatActivity.onCreateContent(SourceFile:195)
12009-16 15:42:12.927 21870 21870 E AndroidRuntime: at com.app.activity.CoreActivity.onCreate(SourceFile:160)
12109-16 15:42:12.927 21870 21870 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:7458)
12209-16 15:42:12.927 21870 21870 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:7448)
12309-16 15:42:12.927 21870 21870 E AndroidRuntime: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
12409-16 15:42:12.927 21870 21870 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
12509-16 15:42:12.927 21870 21870 E AndroidRuntime: ... 11 more
12609-16 15:42:12.927 21870 21870 D MtaSDK : [main(1): null:56] - MTA has caught the following uncaught exception:
12709-16 15:42:12.927 21870 21870 E MtaSDK :
12809-16 15:42:12.927 21870 21870 E MtaSDK : java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yuwan.zbshipin/com.yuwan.meet.activity.P2PChatActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object org.greenrobot.greendao.database.Database.getRawDatabase()' on a null object reference
12909-16 15:42:12.927 21870 21870 E MtaSDK : at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
13009-16 15:42:12.927 21870 21870 E MtaSDK : at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
13109-16 15:42:12.927 21870 21870 E MtaSDK : at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
13209-16 15:42:12.927 21870 21870 E MtaSDK : at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
13309-16 15:42:12.927 21870 21870 E MtaSDK : at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
13409-16 15:42:12.927 21870 21870 E MtaSDK : at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
13509-16 15:42:12.927 21870 21870 E MtaSDK : at android.os.Handler.dispatchMessage(Handler.java:112)
13609-16 15:42:12.927 21870 21870 E MtaSDK : at android.os.Looper.loop(Looper.java:216)
13709-16 15:42:12.927 21870 21870 E MtaSDK : at android.app.ActivityThread.main(ActivityThread.java:7625)
13809-16 15:42:12.927 21870 21870 E MtaSDK : at java.lang.reflect.Method.invoke(Native Method)
13909-16 15:42:12.927 21870 21870 E MtaSDK : at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
14009-16 15:42:12.927 21870 21870 E MtaSDK : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
14109-16 15:42:12.927 21870 21870 E MtaSDK : Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object org.greenrobot.greendao.database.Database.getRawDatabase()' on a null object reference
14209-16 15:42:12.927 21870 21870 E MtaSDK : at org.greenrobot.greendao.AbstractDao.<init>(SourceFile:85)
14309-16 15:42:12.927 21870 21870 E MtaSDK : at com.app.model.dao.bean.ChatUserDMDao.<init>(SourceFile:40)
14409-16 15:42:12.927 21870 21870 E MtaSDK : at com.app.model.dao.bean.DaoSession.<init>(SourceFile:49)
14509-16 15:42:12.927 21870 21870 E MtaSDK : at com.app.model.dao.bean.DaoMaster.newSession(SourceFile:58)
14609-16 15:42:12.927 21870 21870 E MtaSDK : at com.app.model.dao.DaoManager.getDaoSession(SourceFile:67)
14709-16 15:42:12.927 21870 21870 E MtaSDK : at com.app.model.dao.bean.ChatMsgDM.dao(SourceFile:429)
14809-16 15:42:12.927 21870 21870 E MtaSDK : at com.app.greendaoadapter.d.findBy(SourceFile:157)
14909-16 15:42:12.927 21870 21870 E MtaSDK : at com.app.greendaoadapter.d.findAll(SourceFile:177)
15009-16 15:42:12.927 21870 21870 E MtaSDK : at com.app.model.dao.bean.ChatMsgDM.getGroupMessages(SourceFile:761)
15109-16 15:42:12.927 21870 21870 E MtaSDK : at com.app.model.dao.bean.ChatMsgDM.getUserMessages(SourceFile:790)
15209-16 15:42:12.927 21870 21870 E MtaSDK : at com.yuwan.meet.e.av.a(SourceFile:121)
15309-16 15:42:12.927 21870 21870 E MtaSDK : at com.yuwan.meet.activity.P2PChatActivity.onCreateContent(SourceFile:195)
15409-16 15:42:12.927 21870 21870 E MtaSDK : at com.app.activity.CoreActivity.onCreate(SourceFile:160)
15509-16 15:42:12.927 21870 21870 E MtaSDK : at android.app.Activity.performCreate(Activity.java:7458)
15609-16 15:42:12.927 21870 21870 E MtaSDK : at android.app.Activity.performCreate(Activity.java:7448)
15709-16 15:42:12.927 21870 21870 E MtaSDK : at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
15809-16 15:42:12.927 21870 21870 E MtaSDK : at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
15909-16 15:42:12.927 21870 21870 E MtaSDK : ... 11 more
16009-16 15:42:12.934 21870 22096 I MID : read mid from InternalStorage
16109-16 15:42:12.935 21870 22096 I MID : read mid from InternalStorage:xjgD6zAYj0803BSI25xH43SSIJV973m8SnAJpFaX2PhicUBmi+vXgrY0Hzb7T3EJQUN0x+dWSUxrQn5NqA/TZABamvNptcLFULCkSnz857h296AUINU1W0VipnFAFxgpIAZox+SCzb5cMV87xk6GYGaiO0Xu


`

**Comment by greenrobot-team** [comment]
Are you using ProGuard? Check if your rules match those provided in the README.
https://github.com/greenrobot/greenDAO#r8-proguard

**Comment by chenyunecjtu** [comment]
`

org.greenrobot.greendao.AbstractDao.void <init>(org.greenrobot.greendao.internal.DaoConfig,org.greenrobot.greendao.AbstractDaoSession)(SourceFile:85)
--
2 com.app.model.dao.bean.ChatListDMDao.void <init>(org.greenrobot.greendao.internal.DaoConfig,com.app.model.dao.bean.DaoSession)(SourceFile:45)
3 com.app.model.dao.bean.DaoSession.void <init>(org.greenrobot.greendao.database.Database,org.greenrobot.greendao.identityscope.IdentityScopeType,java.util.Map)(SourceFile:49)
4 com.app.model.dao.bean.DaoMaster.com.app.model.dao.bean.DaoSession newSession()(SourceFile:58)
5 com.app.model.dao.DaoManager.com.app.model.dao.bean.DaoSession getDaoSession()(SourceFile:78)
6 com.app.model.dao.bean.ChatMsgDM.org.greenrobot.greendao.AbstractDao dao()(SourceFile:504)
7 com.app.greendaoadapter.DBModel.java.util.List findBy(com.app.greendaoadapter.IDBQuery)(SourceFile:186)
8 com.app.greendaoadapter.DBModel.java.util.List findAll(com.app.greendaoadapter.IDBQuery)(SourceFile:206)
9 com.app.model.dao.bean.ChatMsgDM.boolean readMessage()(SourceFile:755)
10 com.app.model.dao.bean.ChatMsgDM.boolean process()(SourceFile:551)

`

**Comment by chenyunecjtu** [comment]
java.lang.Object org.greenrobot.greendao.database.Database.getRawDatabase() 经常报空指针错误，
